apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: jupyter-hub-secret
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gsm-store             # name of the SecretStore (or kind specified)
  target:
    name: hub-secret            # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          configmanagement.gke.io/cluster-selector: jupyterhub
  dataFrom:
  - key: jupyter-hub-secret
