apiVersion: v1
data:
  jupyterhub_config.py: |
    import os, pwd, grp 
    import sys
    import glob
    import kubespawner
    import kubernetes
    from pprint import pprint
    from tornado.httpclient import AsyncHTTPClient
    
    AsyncHTTPClient.configure("tornado.curl_httpclient.CurlAsyncHTTPClient")
    
    c.JupyterHub.template_vars = {
        'announcement_login': '''***********************************************************************<br/>
      System is designed for high risk data; you still must comply with all<br/>
               applicable Stanford policies for high risk data.<br/>
    ***********************************************************************<br/>
     This system is for authorized users only and users must comply with all<br/>
     Stanford computing, network and research policies. All activity may be<br/>
     recorded for security and monitoring purposes. For more information, see<br/>
     https://doresearch.stanford.edu/policies/research-policy-handbook and<br/>
     https://adminguide.stanford.edu/chapters/computing/computer-and-network-usage/computer-and-network-usage-policy<br/>
    ***********************************************************************'''
    }
    
    c.JupyterHub.spawner_class = 'kubespawner.KubeSpawner'
    c.ConfigurableHTTPProxy.api_url = 'http://proxy-api.jupyter.svc.cluster.local:8001'
    c.ConfigurableHTTPProxy.should_start = False
    c.JupyterHub.cleanup_servers = False
    c.JupyterHub.last_activity_interval = 60
    c.JupyterHub.ip = '10.152.68.110'
    c.JupyterHub.port = 8081
    c.JupyterHub.hub_ip = '0.0.0.0'
    c.KubeSpawner.start_timeout = 300
    c.KubeSpawner.http_timeout = 120
    # todo: using image built 20250218 (fd#81627) but only for jupyter
    #       current production image 268b9bb used everywhere else.
    c.KubeSpawner.image = 'us-docker.pkg.dev/srcc-nero-prod/docker-repo/jupyter-20.04:ba3c28e'
    c.KubeSpawner.image_pull_secrets = [{"name": "artifact-registry"}]
    c.KubeSpawner.pod_connect_ip = 'jupyter.{username}.svc.cluster.local'
    c.KubeSpawner.automount_service_account_token = True
    c.KubeSpawner.node_selector = {'app': 'jupyter'}
    service_account_name = 'hub'
    storage_type = 'dynamic'
    if storage_type == 'dynamic':
        c.KubeSpawner.pvc_name_template = 'claim-{username}{servername}'
        c.KubeSpawner.storage_pvc_ensure = False
        storage_class = None
        if storage_class:
            c.KubeSpawner.user_storage_class = storage_class
        c.KubeSpawner.storage_access_modes = ['ReadWriteOnce']
        c.KubeSpawner.storage_capacity = '10Gi'
        c.KubeSpawner.volumes = [
            {
                'name': 'modulefiles',
                'hostPath': {
                    'path': '/mnt/srcc/modulefiles',
                    'type': 'Directory'
                }
            },
            {
                'name': 'temp',
                'emptyDir': {}
            },
            {
                'name': 'extrausers',
                'configMap': {
                    'name': 'extrausers'
                }
            },
            {
                'name': 'munge-key',
                'secret': {
                    'secretName': 'munge-key'
                }
            },
            {
                'name': 'munge-run',
                'hostPath': {
                    'path': '/mnt/srcc/munge',
                    'type': 'Directory'
                }
            },
            {
                'name': 'slurm-node-conf',
                'configMap': {
                    'name': 'slurm-node-conf'
                }
            },
            {
                'name': 'share-pi',
                'persistentVolumeClaim': {
                    'claimName': 'cephfs-static-pi'
                }
            },
            {
                'name': 'share-sw',
                'nfs': {
                    'server': '10.152.14.101',
                    'path': '/'
                }
            }
        ]
        c.KubeSpawner.volume_mounts = [
            {
                'mountPath': '/usr/share/lmod/lmod/modulefiles',
                'name': 'modulefiles',
                'readOnly': True
            },
            {
                'mountPath': '/tmp',
                'name': 'temp'
            },
            {
                'mountPath': '/var/lib/extrausers',
                'name': 'extrausers'
            },
            {
                'mountPath': '/var/run/munge',
                'name': 'munge-run'
            },
            {
                'mountPath': '/local/munge-key',
                'name': 'munge-key'
            },
            {
                'mountPath': '/etc/slurm-llnl',
                'name': 'slurm-node-conf'
            },
            {
                'mountPath': '/share/pi',
                'name': 'share-pi',
                'subPath': 'pi'
            },
            {
                'mountPath': '/share/data',
                'name': 'share-pi',
                'subPath': 'data'
            },
            {
                'mountPath': '/share/sw',
                'name': 'share-sw',
                'subPath': 'share/sw',
                'readOnly': True
            }
        ]
    c.KubeSpawner.hub_connect_ip = 'hub.jupyter.svc.cluster.local'
    c.KubeSpawner.hub_connect_port = int(os.environ['HUB_SERVICE_PORT'])
    c.JupyterHub.hub_connect_ip = 'hub.jupyter.svc.cluster.local'
    c.JupyterHub.hub_connect_url = 'http://hub.jupyter.svc.cluster.local:8081'
    c.KubeSpawner.mem_limit = '32G'
    c.KubeSpawner.mem_guarantee = '1G'
    c.KubeSpawner.cpu_limit = 8
    c.KubeSpawner.cpu_guarantee = 1
    auth_type = 'google'
    email_domain = 'local'
    if auth_type == 'google':
        c.JupyterHub.authenticator_class = 'oauthenticator.GoogleOAuthenticator'
        c.GoogleOAuthenticator.client_id = '802938244258-uce3v51n1ts3n8biihg6412toi7ngego.apps.googleusercontent.com'
        c.GoogleOAuthenticator.client_secret = 'UcvYtPbkyfXdRLN-ZtTqddHz'
        c.GoogleOAuthenticator.oauth_callback_url = 'https://www.onprem.carina.stanford.edu/hub/oauth_callback'
        c.GoogleOAuthenticator.hosted_domain = 'stanford.edu'
        c.GoogleOAuthenticator.login_service = 'Stanford University'
        email_domain = 'stanford.edu'
    elif auth_type == 'github':
        c.JupyterHub.authenticator_class = 'oauthenticator.GitHubOAuthenticator'
        c.GitHubOAuthenticator.oauth_callback_url = get_config('auth.github.callback-url')
        c.GitHubOAuthenticator.client_id = get_config('auth.github.client-id')
        c.GitHubOAuthenticator.client_secret = get_config('auth.github.client-secret')
    elif auth_type == 'cilogon':
        c.JupyterHub.authenticator_class = 'oauthenticator.CILogonOAuthenticator'
        c.CILogonOAuthenticator.oauth_callback_url = get_config('auth.cilogon.callback-url')
        c.CILogonOAuthenticator.client_id = get_config('auth.cilogon.client-id')
        c.CILogonOAuthenticator.client_secret = get_config('auth.cilogon.client-secret')
    elif auth_type == 'gitlab':
        c.JupyterHub.authenticator_class = 'oauthenticator.gitlab.GitLabOAuthenticator'
        c.GitLabOAuthenticator.oauth_callback_url = get_config('auth.gitlab.callback-url')
        c.GitLabOAuthenticator.client_id = get_config('auth.gitlab.client-id')
        c.GitLabOAuthenticator.client_secret = get_config('auth.gitlab.client-secret')
    elif auth_type == 'mediawiki':
        c.JupyterHub.authenticator_class = 'oauthenticator.mediawiki.MWOAuthenticator'
        c.MWOAuthenticator.client_id = get_config('auth.mediawiki.client-id')
        c.MWOAuthenticator.client_secret = get_config('auth.mediawiki.client-secret')
        c.MWOAuthenticator.index_url = get_config('auth.mediawiki.index-url')
    elif auth_type == 'globus':
        c.JupyterHub.authenticator_class = 'oauthenticator.globus.GlobusOAuthenticator'
        c.GlobusOAuthenticator.oauth_callback_url = get_config('auth.globus.callback-url')
        c.GlobusOAuthenticator.client_id = get_config('auth.globus.client-id')
        c.GlobusOAuthenticator.client_secret = get_config('auth.globus.client-secret')
        c.GlobusOAuthenticator.identity_provider = get_config('auth.globus.identity-provider', '')
    elif auth_type == 'hmac':
        c.JupyterHub.authenticator_class = 'hmacauthenticator.HMACAuthenticator'
        c.HMACAuthenticator.secret_key = bytes.fromhex(get_config('auth.hmac.secret-key'))
    elif auth_type == 'dummy':
        c.JupyterHub.authenticator_class = 'dummyauthenticator.DummyAuthenticator'
        c.DummyAuthenticator.password = get_config('auth.dummy.password', None)
    elif auth_type == 'tmp':
        c.JupyterHub.authenticator_class = 'tmpauthenticator.TmpAuthenticator'
    elif auth_type == 'lti':
        c.JupyterHub.authenticator_class = 'ltiauthenticator.LTIAuthenticator'
        c.LTIAuthenticator.consumers = get_config('auth.lti.consumers')
    elif auth_type == 'custom':
        full_class_name = get_config('auth.custom.class-name')
        c.JupyterHub.authenticator_class = full_class_name
        auth_class_name = full_class_name.rsplit('.', 1)[-1]
        auth_config = c[auth_class_name]
        auth_config.update(get_config('auth.custom.config') or {})
    else:
        raise ValueError("Unhandled auth type: %r" % auth_type)
    c.Authenticator.enable_auth_state = False
    def generate_user_email(spawner):
        """
        Used as the EMAIL environment variable
        """
        return '{username}@{domain}'.format(
            username=spawner.user.name, domain=email_domain
        )
    def generate_user_name(spawner):
        """
        Used as GIT_AUTHOR_NAME and GIT_COMMITTER_NAME environment variables
        """
        return spawner.user.name
    c.KubeSpawner.environment = {
        'EMAIL': generate_user_email,
        'GIT_AUTHOR_NAME': generate_user_name,
        'GIT_COMMITTER_NAME': generate_user_name
    }
    c.JupyterHub.admin_access = True
    c.Authenticator.admin_users = ['vmeau','neals','addiso','wlaw']
    c.Authenticator.allowed_users = ['mpiercy','lesleyp','sbogdan']
    def my_hook(spawner):
       username = spawner.user.name
       myuid = pwd.getpwnam(username).pw_uid
       mygroups = [g.gr_gid for g in grp.getgrall() if username in g.gr_mem]
       mygid = pwd.getpwnam(username).pw_gid
       spawner.uid = myuid
       spawner.gid = mygid
       spawner.supplemental_gids = mygroups
    c.KubeSpawner.pre_spawn_hook = my_hook
    c.KubeSpawner.enable_user_namespaces = True
    c.KubeSpawner.user_namespace_template = '{username}'
    pprint(vars(c.KubeSpawner))
    pprint(vars(c.Authenticator))
    pprint(vars(c.JupyterHub))
    c.JupyterHub.base_url = '/'
    c.JupyterHub.load_roles = [
        {
            "name": "jupyterhub-idle-culler-role",
            "scopes": [
                "list:users",
                "read:users:activity",
                "read:servers",
                "delete:servers"
            ],
            "services": ["jupyterhub-idle-culler-service"],
        }
    ]
    c.JupyterHub.services = [
        {
            "name": "jupyterhub-idle-culler-service",
            "command": [
                sys.executable,
                "-m", "jupyterhub_idle_culler",
                "--timeout=28800",
            ],
            # "admin": True,
        }
    ]
    c.JupyterHub.db_url = 'sqlite:///jupyterhub.sqlite'
    c.JupyterHub.db.type = 'sqlite-pvc'
    cmd = '/usr/local/bin/new-start-notebook.sh'
    if cmd:
        c.Spawner.cmd = cmd
    c.Spawner.default_url = "/lab"
    network_tools_image_name = 'jupyterhub/k8s-network-tools'
    network_tools_image_tag = 'latest'
    scheduler_strategy = 'spread'
    if scheduler_strategy == 'pack':
        c.KubeSpawner.extra_pod_config = {
            'affinity': {
                'podAffinity': {
                    'preferredDuringSchedulingIgnoredDuringExecution': [{
                        'weight': 100,
                        'podAffinityTerm': {
                            'labelSelector': {
                                'matchExpressions': [{
                                    'key': 'component',
                                    'operator': 'In',
                                    'values': ['singleuser-server']
                                }]
                            },
                            'topologyKey': 'kubernetes.io/hostname'
                        }
                    }],
                }
            }
        }
    else:
        c.KubeSpawner.extra_pod_config = {}
    extra_configs = sorted(glob.glob('/etc/jupyterhub/config/hub.extra-config.*.py'))
    for ec in extra_configs:
        load_subconfig(ec)
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: jupyterhub-config
  namespace: jupyter
