# ./users/sthiell/kustomization.yaml
namespace: sthiell

resources:
- ../../base/user
- ../../base/configmaps


patches:
- target:
    kind: Namespace
    name: default
  patch: |-
    - op: replace
      path: /metadata/name
      value: sthiell
- target:
    kind: PersistentVolume
    name: cephfs-static-home
  patch: |-
    - op: replace
      path: /metadata/name
      value: cephfs-static-home-sthiell
    - op: replace
      path: /spec/csi/volumeHandle
      value: cephfs-static-home-sthiell
- target:
    kind: PersistentVolume
    name: cephfs-static-pi
  patch: |-
    - op: replace
      path: /metadata/name
      value: cephfs-static-pi-sthiell
    - op: replace
      path: /spec/csi/volumeHandle
      value: cephfs-static-pi-sthiell
- target:
    kind: PersistentVolumeClaim
    name: cephfs-static-home
  patch: |-
    - op: replace
      path: /spec/volumeName
      value: cephfs-static-home-sthiell
- target:
    kind: PersistentVolumeClaim
    name: cephfs-static-pi
  patch: |-
    - op: replace
      path: /spec/volumeName
      value: cephfs-static-pi-sthiell
- target:
    kind: Service
    name: jupyter
  patch: |-
    - op: replace
      path: /spec/selector/hub.jupyter.org~1username
      value: sthiell
