- ansible.builtin.include_tasks:
    file: postfix.yml
    apply:
      tags:
        - postfix
  tags:
    - always

- ansible.builtin.include_tasks:
    file: slurmctld.yml
    apply:
      tags:
        - slurmctld
  tags:
    - always

#- ansible.builtin.include_tasks:
#    file: slurmrestd.yml
#    apply:
#      tags:
#        - slurmrestd
#  tags:
#    - always
