- name: install packages
  ansible.builtin.dnf:
    name:
      - postfix
      - s-nail
    state: present
    update_cache: yes

- name: install /etc/postfix/main.cf
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '00644'
  register: pstfxsrv

- name: install /etc/postfix/generic
  ansible.builtin.template:
    src: generic.j2
    dest: /etc/postfix/generic
    owner: root
    group: root
    mode: '00644'
  register: pstfxgrc

- name: update postfix generic lookup table
  ansible.builtin.command:
    cmd: postmap lmdb:/etc/postfix/generic
  when: pstfxgrc is changed

- name: start/restart and enable postfix.service
  ansible.builtin.systemd_service:
    name: postfix.service
    state: "{{ 'restarted' if pstfxsrv.changed or pstfxgrc.changed else 'started' }}"
    enabled: yes
    daemon_reload: yes
