- name: install packages
  ansible.builtin.dnf:
    name:
      - slurm-slurmctld-{{ slurm_version }}
    state: present
    update_cache: yes
    enablerepo: c2-local

- name: create directory /etc/slurm
  ansible.builtin.file:
    path: /etc/slurm
    state: directory
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"

- name: create directory /var/spool/slurmctld
  ansible.builtin.file:
    path: /var/spool/slurmctld
    state: directory
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"

- name: install /etc/slurm/{cgroup,gres,slurm}.conf
  ansible.builtin.template:
    src: "{{ item }}.conf.j2"
    dest: /etc/slurm/{{ item }}.conf
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: '00600'
  loop:
    - cgroup
    - gres
    - slurm
  register: sctldcnf

- name: Install prolog/epilog scripts
  ansible.builtin.template:
    src: "{{ item }}.sh.j2"
    dest: /etc/slurm/{{ item }}.sh
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: '0755'
  loop:
    - prolog
    - taskprolog
    - epilog
  register: sctldscrpt

#- name: install /etc/systemd/system/slurmctld.service
#  ansible.builtin.template:
#    src: slurmctld.service.j2
#    dest: /etc/systemd/system/slurmctld.service
#    owner: root
#    group: root
#    mode: '00644'
#  register: sctldsrv

- name: install /etc/sysconfig/slurmctld
  ansible.builtin.copy:
    src: etc/sysconfig/slurmctld
    dest: /etc/sysconfig/slurmctld
    owner: root
    group: root
    mode: '00644'
  register: sctldsc

  - name: install partition qos script
  ansible.builtin.template:
    src: slurm-partition-qos.j2
    dest: /admin/bin/slurm-partition-qos
    owner: root
    group: root
    mode: '0700'
  notify: "run partition qos" 

- name: start/restart and enable slurmctld.service
  ansible.builtin.systemd_service:
    name: slurmctld.service
    #state: "{{ 'restarted' if sctldcnf.changed or sctldsrv.changed or sctldsc.changed else 'started' }}"
    state: "{{ 'restarted' if sctldcnf.changed or sctldsc.changed or sctldscrpt.changed else 'started' }}"
    enabled: yes
    daemon_reload: yes
