- name: create group {{ slurmrestd_group }}
  ansible.builtin.group:
    name: "{{ slurmrestd_group }}"
    gid: "{{ slurmrestd_gid }}"

- name: create user {{ slurmrestd_user }}
  ansible.builtin.user:
    name: "{{ slurmrestd_user }}"
    uid: "{{ slurmrestd_uid }}"
    group: "{{ slurmrestd_group }}"
    home: /nonexistent
    create_home: no
    shell: /usr/sbin/nologin

- name: install packages
  ansible.builtin.dnf:
    name:
      - slurm-slurmrestd-{{ slurm_version }}
    state: present
    update_cache: yes
    enablerepo: c2-local

#- name: install /etc/systemd/system/slurmrestd.service
#  ansible.builtin.copy:
#    src: slurmrestd.service.j2
#    dest: /etc/systemd/system/slurmrestd.service
#    owner: root
#    group: root
#    mode: '00644'
#  register: srstdsrv

- name: install /etc/sysconfig/slurmrestd
  ansible.builtin.copy:
    src: etc/sysconfig/slurmrestd
    dest: /etc/sysconfig/slurmrestd
    owner: root
    group: root
    mode: '00644'
  register: srstdsc

- name: start/restart and enable slurmrestd.service
  ansible.builtin.systemd_service:
    name: slurmrestd.service
    #state: "{{ 'restarted' if srstdsrv.changed or srstdsc.changed else 'started' }}"
    state: "{{ 'restarted' if srstdsc.changed else 'started' }}"
    enabled: yes
    daemon_reload: yes
