- name: create group {{ prometheus_group }}
  ansible.builtin.group:
    name: "{{ prometheus_group }}"
    gid: "{{ prometheus_gid }}"

- name: create user {{ prometheus_user }}
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    uid: "{{ prometheus_uid }}"
    group: "{{ prometheus_group }}"
    home: /nonexistent
    create_home: no
    shell: /usr/sbin/nologin

- name: fetch prometheus tarball
  ansible.builtin.get_url:
    url: "{{ prometheus_tgz_url }}"
    dest: /var/tmp/{{ prometheus_tgz }}
    checksum: "sha256:{{ prometheus_tgz_sha256 }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0644'

- name: extract prometheus tarball
  ansible.builtin.unarchive:
    src: /var/tmp/{{ prometheus_tgz }}
    dest: /var/tmp
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    remote_src: yes

- name: copy prometheus binary to /usr/local/sbin
  ansible.builtin.copy:
    src: /var/tmp/{{ prometheus_tgz_dir }}/prometheus
    dest: /usr/local/sbin/prometheus
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0750'
    remote_src: yes

- name: create directory /etc/prometheus
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: install /etc/prometheus/prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'
  register: promyml

- name: create directory {{ prometheus_data_dir }}
  ansible.builtin.file:
    path: "{{ prometheus_data_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'

- name: create directory {{ prometheus_log_dir }}
  ansible.builtin.file:
    path: "{{ prometheus_log_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'

- name: install /etc/systemd/system/prometheus.service
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'
  register: promsrv

- name: start/restart and enable prometheus.service
  ansible.builtin.systemd_service:
    name: prometheus.service
    state: "{{ 'restarted' if promyml.changed or promsrv.changed else 'started' }}"
    enabled: yes
    daemon_reload: yes
