- ansible.builtin.include_tasks:
    file: virt.yml
    apply:
      tags:
        - virt
  tags:
    - always

- ansible.builtin.include_tasks:
    file: virt-net.yml
    apply:
      tags:
        - virt-net
  tags:
    - always

- ansible.builtin.include_tasks:
    file: virt-pool.yml
    apply:
      tags:
        - virt-pool
  tags:
    - always
