# ./users/mottaghi/kustomization.yaml
namespace: mottaghi

resources:
- ../../base/user
- ../../base/configmaps


patches:
- target:
    kind: Namespace
    name: default
  patch: |-
    - op: replace
      path: /metadata/name
      value: mottaghi
- target:
    kind: PersistentVolume
    name: cephfs-static-home
  patch: |-
    - op: replace
      path: /metadata/name
      value: cephfs-static-home-mottaghi
    - op: replace
      path: /spec/csi/volumeHandle
      value: cephfs-static-home-mottaghi
- target:
    kind: PersistentVolume
    name: cephfs-static-pi
  patch: |-
    - op: replace
      path: /metadata/name
      value: cephfs-static-pi-mottaghi
    - op: replace
      path: /spec/csi/volumeHandle
      value: cephfs-static-pi-mottaghi
- target:
    kind: PersistentVolumeClaim
    name: cephfs-static-home
  patch: |-
    - op: replace
      path: /spec/volumeName
      value: cephfs-static-home-mottaghi
- target:
    kind: PersistentVolumeClaim
    name: cephfs-static-pi
  patch: |-
    - op: replace
      path: /spec/volumeName
      value: cephfs-static-pi-mottaghi
- target:
    kind: Service
    name: jupyter
  patch: |-
    - op: replace
      path: /spec/selector/hub.jupyter.org~1username
      value: mottaghi
