apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-mgmt-db
  namespace: user-mgmt
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25G
  volumeMode: Filesystem
  volumeName: user-mgmt-db
