#!/bin/bash

ME="$( basename "$( readlink -f "$0" )" )"
DIR="$( cd "$( dirname "$( readlink -f "$0" )" )" && pwd )"
DIR="$( dirname $DIR )"
GROUP="$DIR/base/configmaps/group"
GSHADOW="$DIR/base/configmaps/gshadow"
PASSWD="$DIR/base/configmaps/passwd"
SHADOW="$DIR/base/configmaps/shadow"
LDAPBASE="cn=accounts,dc=stanford,dc=edu"
LDAPURL="ldap://ldap.stanford.edu"

if [ "$( uname -s )" != "Linux" ]
then
  echo "$ME must be run on Linux" >&2
  exit 1
fi

if ! which ldapsearch >/dev/null
then
  echo "ldapsearch is not installed" >&2
  exit 1
fi

usage()
{
  echo "usage: $ME [--piproject ...] --pisunetid <pisunetid> [<sunetid> ...]" >&2
  exit 1
}

sunetid_valid()
{
  local SUNETID
  SUNETID="$1"
  test -n "$( ldapsearch -b $LDAPBASE -H $LDAPURL -LLL -x uid=$SUNETID dn )"
}

get_gecos()
{
  local SUNETID GECOS
  SUNETID="$1"
  GECOS="$( ldapsearch -b $LDAPBASE -H $LDAPURL -LLL -x uid=$SUNETID gecos | grep ^gecos: | sed 's~^gecos: ~~' )"
  echo "$GECOS"
}

group_exists()
{
  local GRP
  GRP="$1"
  grep -q "^$GRP:" $GROUP
}

user_exists()
{
  local USR
  USR="$1"
  grep -q "^$USR:" $PASSWD
}

user_in_group()
{
  local USR GRP
  USR="$1"
  GRP="$2"
  grep "^$GRP:" $GROUP | grep -q $USR
}

next_pi_gid()
{
  local LASTID
  LASTID="$( egrep -- '-pi(|-.*):x' $GROUP | cut -d: -f3 | sort -n | tail -1 )"
  echo "$(( LASTID + 1 ))"
}

next_user_gid()
{
  local LASTID
  LASTID="$( egrep -v '^carina_|-pi(|-.*):x' $GROUP | cut -d: -f3 | sort -n | tail -1 )"
  echo "$(( LASTID + 1 ))"
}

OPTS=$( getopt --name "$ME" --longoptions piproject:,pisunetid: --options "" --quiet -- "$@" ) || usage
eval set -- "$OPTS"

while true
do
  case "$1" in
    --piproject) PIPROJECT="$2"; shift 2 ;;
    --pisunetid) PISUNETID="$2"; shift 2 ;;
    --) shift; break ;;
    *) break ;;
  esac
done

[ -n "$PISUNETID" ] || usage
PIGROUP="$PISUNETID-pi"
[ -n "$PIPROJECT" ] && PIGROUP="$PIGROUP-$PIPROJECT"

if ! sunetid_valid $PISUNETID
then
  echo "pisunetid $PISUNETID is not a valid sunetid" >&2
  exit 1
fi

if [ -n "$*" ]
then
  for SUNETID in "$@"
  do
    if ! sunetid_valid $SUNETID
    then
      echo "sunetid $SUNETID is not a valid sunetid" >&2
      exit 1
    fi
  done
fi

if ! group_exists $PISUNETID
then
  PIUSRGID="$( next_user_gid )"
  echo "adding group $PISUNETID"
  echo "$PISUNETID:x:$PIUSRGID:" >> $GROUP
  echo "$PISUNETID:!::" >> $GSHADOW
else
  echo "group $PISUNETID already exists"
fi

if ! group_exists $PIGROUP
then
  echo "adding group $PIGROUP"
  echo "$PIGROUP:x:$( next_pi_gid ):$PISUNETID" >> $GROUP
  echo "$PIGROUP:!::$PISUNETID" >> $GSHADOW
else
  echo "group $PIGROUP already exists"
fi

if ! user_in_group $PISUNETID carina_users
then
  echo "adding user $PISUNETID to group carina_users"
  sed -i -E "s~^(carina_users:.*)$~\1,$PISUNETID~" $GROUP
  sed -i -E "s~^(carina_users:.*)$~\1,$PISUNETID~" $GSHADOW
else
  echo "user $PISUNETID is already in group carina_users"
fi

if ! user_exists $PISUNETID
then
  echo "adding user $PISUNETID"
  GECOS="$( get_gecos $PISUNETID )"
  if [ -n "$GECOS" ]
  then
    echo "$PISUNETID:x:$PIUSRGID:$PIUSRGID:$GECOS,,,:/home/$PISUNETID:/bin/bash" >> $PASSWD
  else
    echo "$PISUNETID:x:$PIUSRGID:$PIUSRGID:$PISUNETID,,,:/home/$PISUNETID:/bin/bash" >> $PASSWD
  fi
  echo "$PISUNETID:*:17734:0:99999:7:::" >> $SHADOW
  echo "- $PISUNETID" >> $DIR/users/kustomization.yaml
  mkdir -p $DIR/users/$PISUNETID
  sed "s~{{SUNET_ID}}~$PISUNETID~" $DIR/scripts/new_user_kustomization.yaml > $DIR/users/$PISUNETID/kustomization.yaml
else
  echo "user $PISUNETID already exists"
fi

if [ -n "$*" ]
then
  for SUNETID in "$@"
  do

    if ! group_exists $SUNETID
    then
      USRGID="$( next_user_gid )"
      echo "adding group $SUNETID"
      echo "$SUNETID:x:$USRGID:" >> $GROUP
      echo "$SUNETID:!::" >> $GSHADOW
    else
      echo "group $SUNETID already exists"
    fi
    
    if ! user_in_group $SUNETID carina_users
    then
      echo "adding user $SUNETID to group carina_users"
      sed -i -E "s~^(carina_users:.*)$~\1,$SUNETID~" $GROUP
      sed -i -E "s~^(carina_users:.*)$~\1,$SUNETID~" $GSHADOW
    else
      echo "user $SUNETID is already in group carina_users"
    fi
    
    if ! user_in_group $SUNETID $PIGROUP
    then
      echo "adding user $SUNETID to group $PIGROUP"
      sed -i -E "s~^($PIGROUP:.*)$~\1,$SUNETID~" $GROUP
      sed -i -E "s~^($PIGROUP:.*)$~\1,$SUNETID~" $GSHADOW
    else
      echo "user $SUNETID is already in group $PIGROUP"
    fi
    
    if ! user_exists $SUNETID
    then
      echo "adding user $SUNETID"
      GECOS="$( get_gecos $SUNETID )"
      if [ -n "$GECOS" ]
      then
        echo "$SUNETID:x:$USRGID:$USRGID:$GECOS,,,:/home/$SUNETID:/bin/bash" >> $PASSWD
      else
        echo "$SUNETID:x:$USRGID:$USRGID:$SUNETID,,,:/home/$SUNETID:/bin/bash" >> $PASSWD
      fi
      echo "$SUNETID:*:17734:0:99999:7:::" >> $SHADOW
      echo "- $SUNETID" >> $DIR/users/kustomization.yaml
      mkdir -p $DIR/users/$SUNETID
      sed "s~{{SUNET_ID}}~$SUNETID~" $DIR/scripts/new_user_kustomization.yaml > $DIR/users/$SUNETID/kustomization.yaml
    else
      echo "user $SUNETID already exists"
    fi

  done
fi

sort -o $GROUP $GROUP
sort -o $GSHADOW $GSHADOW
sort -o $PASSWD $PASSWD
sort -o $SHADOW $SHADOW
