---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "cc06bc72-cacd-11eb-8bdd-97416ba6ca5f",
        "monitors": [
          "192.168.2.17",
          "192.168.2.26",
          "192.168.2.6"
        ]
      }
    ]
metadata:
  name: ceph-csi-config
  annotations:
    configmanagement.gke.io/cluster-selector: selector-ceph
