apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ceph-rbd-keyring
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gsm-store             # name of the SecretStore (or kind specified)
  target:
    name: rbd-keyring             # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          configmanagement.gke.io/cluster-selector: selector-ceph
  data:
  - secretKey: kubernetes-rbd-provisioner.keyring        # name of the GCPSM secret key
    remoteRef:
      key: ceph-rbd-keyring
