- name: install /etc/dnsmasq.conf
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
    validate: /usr/sbin/dnsmasq --conf-file=%s --test
  register: dnsmasqconf

- name: restart dnsmasq
  ansible.builtin.systemd_service:
    name: dnsmasq.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: dnsmasqconf is changed
