apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: csi-cephfs-pi-client-secret
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gsm-store             # name of the SecretStore (or kind specified)
  target:
    name: csi-cephfs-pi-client-secret     # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          configmanagement.gke.io/cluster-selector: selector-ceph
  dataFrom:
  - key: csi-cephfs-pi-client-secret
