- name: install packages
  ansible.builtin.dnf:
    name:
      - http-parser
      - json-c
      - libyaml
      - munge
      - slurm-{{ slurm_version }}
      - slurm-contribs-{{ slurm_version }}
      - slurm-perlapi-{{ slurm_version }}
    state: present
    update_cache: yes
    enablerepo: c2-local
  tags:
    - packages

- name: install /etc/munge/munge.key
  ansible.builtin.copy:
    content: "{{ lookup('env', 'MUNGE_KEY_B64') | b64decode }}"
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0600'
  register: mngky

- name: install /etc/sysconfig/munge
  ansible.builtin.template:
    src: munge.j2
    dest: /etc/sysconfig/munge
    owner: root
    group: root
    mode: '00644'
  register: mngsc

- name: start/restart and enable munge.service
  ansible.builtin.systemd_service:
    name: munge.service
    state: "{{ 'restarted' if mngky.changed or mngsc.changed else 'started' }}"
    enabled: yes
    daemon_reload: yes

- name: create group {{ slurm_group }}
  ansible.builtin.group:
    name: "{{ slurm_group }}"
    gid: "{{ slurm_gid }}"

- name: create user {{ slurm_user }}
  ansible.builtin.user:
    name: "{{ slurm_user }}"
    uid: "{{ slurm_uid }}"
    group: "{{ slurm_group }}"
    home: /nonexistent
    create_home: no
    shell: /usr/sbin/nologin

- name: create directory /var/log/slurm
  ansible.builtin.file:
    path: /var/log/slurm
    state: directory
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"

- name: create directory /var/run/slurm
  ansible.builtin.file:
    path: /var/run/slurm
    state: directory
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
