- ansible.builtin.include_tasks:
    file: ssh.yml
    apply:
      tags:
        - ssh
  tags:
    - always

- ansible.builtin.include_tasks:
    file: ood.yml
    apply:
      tags:
        - ood
  tags:
    - always

- ansible.builtin.include_tasks:
    file: user-slice-resource-limits.yml
    apply:
      tags:
        - user-slice-resource-limits
  tags:
    - always
