- name: create directory /etc/skel/Desktop
  ansible.builtin.file:
    path: /etc/skel/Desktop
    state: directory

# nb: /usr/share/applications/SAS94.desktop
#     installed in role c2-compute-node .
- name: install symlink /etc/skel/Desktop/SAS94.desktop
  ansible.builtin.file:
    src: /usr/share/applications/SAS94.desktop
    dest: /etc/skel/Desktop/SAS94.desktop
    state: link
    force: yes
