- name: install /etc/ssh/ssh_host_{ecdsa,ed25519,rsa}_key{,.pub}
  ansible.builtin.copy:
    content: |
      {{ lookup('env', item.envvar) }}
    dest: "{{ item.file }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ login_ssh_host_keys }}"
  register: sshkeys

- name: restart sshd.service
  ansible.builtin.systemd_service:
    name: sshd.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: sshkeys.changed

- name: install /etc/ssh/ssh_known_hosts
  ansible.builtin.copy:
    content: |
      {% for pkev in compute_ssh_host_public_key_envvars %}
      {{ groups['c2_compute_node'] | join(',') }} {{ lookup('env', pkev) }}
      {% endfor %}
    dest: /etc/ssh/ssh_known_hosts
    owner: root
    group: root
    mode: '00644'
  vars:
    compute_ssh_host_public_key_envvars:
      - COMPUTE_NODE_SSH_ECDSA_PUBLIC_KEY
      - COMPUTE_NODE_SSH_ED25519_PUBLIC_KEY
      - COMPUTE_NODE_SSH_RSA_PUBLIC_KEY
