- name: install packages for gpu
  ansible.builtin.dnf:
    name:
      - cuda-driver
      - cuda-toolkit
      - dkms # repo: epel
    state: present
    update_cache: yes
    enablerepo:
      - cuda-rhel{{ distros[distro]['version_major'] }}-x86_64
      - epel
