- name: install packages for gpu
  ansible.builtin.dnf:
    name:
      - cuda
      - "@development"
      - dkms # repo: epel
    state: present
    update_cache: yes
    enablerepo:
      - cuda-rhel{{ distros[distro]['version_major'] }}-x86_64
      - epel

- name: run nvidia-smi to trigger creation of /dev/nvidia*
  ansible.builtin.command:
    cmd: /usr/bin/nvidia-smi
  changed_when: false
