- ansible.builtin.include_tasks:
    file: gpu.yml
    apply:
      tags:
        - gpu
  tags:
    - always
  when: inventory_hostname in groups['c2_gpu_node']

- ansible.builtin.include_tasks:
    file: slurm.yml
    apply:
      tags:
        - slurm
  tags:
    - always

- ansible.builtin.include_tasks:
    file: ood.yml
    apply:
      tags:
        - ood
  tags:
    - always

- ansible.builtin.include_tasks:
    file: local-scratch.yml
    apply:
      tags:
        - disk-config
  tags:
    - always
