- name: install packages for ood interactive apps
  ansible.builtin.dnf:
    name:
      - code-server # repo: c2-local
      # nmap-ncat is installed in role c2-base-os
      - python3-websockify # repo: epel
      - rstudio-server # repo: c2-local
      - turbovnc # repo: turbovnc
      - "@xfce-desktop" # repo: epel
    state: present
    update_cache: yes
    disable_gpg_check: yes
    enablerepo:
      - c2-local
      - epel
      - turbovnc

- name: stop/disable rstudio-server.service
  ansible.builtin.systemd_service:
    name: rstudio-server.service
    state: stopped
    enabled: no
    daemon_reload: yes

# nb: /etc/skel/Desktop/SAS94.desktop
#     symlink installed in role c2-login-node .
- name: install sas desktop file
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Version=1.0
      Type=Application
      Name=SAS 9.4
      GenericName=SAS
      Exec=/software/modules/sas/9.4/SASHome/SASFoundation/9.4/sas
      Icon=/software/modules/sas/9.4/SASHome/saslogo.png
      Terminal=true
      StartupNotify=true
    dest: /usr/share/applications/SAS94.desktop
    mode: '00644'

- name: install /usr/local/sbin/proot
  ansible.builtin.get_url:
    url: "{{ proot_binary_url }}"
    dest: /usr/local/sbin/proot
    checksum: "sha256:{{ proot_binary_sha256 }}"
    owner: root
    group: root
    mode: '00755'

- name: install package ncurses-compat-libs (provides libncurses.so.5 for stata)
  ansible.builtin.dnf:
    name: ncurses-compat-libs # repo: devel
    state: present
    update_cache: yes
    enablerepo: devel
