- name: install packages for ood interactive apps
  ansible.builtin.dnf:
    name:
      - code-server # repo: c2-local
      # nmap-ncat is installed in role c2-base-os
      - python3-websockify # repo: epel
      - rstudio-server # repo: c2-local
      - turbovnc # repo: turbovnc
      - "@xfce-desktop" # repo: epel
    state: present
    update_cache: yes
    disable_gpg_check: yes
    enablerepo:
      - c2-local
      - epel
      - turbovnc

- name: stop/disable rstudio-server.service
  ansible.builtin.systemd_service:
    name: rstudio-server.service
    state: stopped
    enabled: no
    daemon_reload: yes
