- name: install packages for slurm
  ansible.builtin.dnf:
    name:
      - slurm-pam_slurm-{{ slurm_version }}
      - slurm-slurmd-{{ slurm_version }}
    state: present
    update_cache: yes
    enablerepo: c2-local

- name: create directory /var/spool/slurmd
  ansible.builtin.file:
    path: /var/spool/slurmd
    state: directory
    owner: root
    group: root

- name: install /etc/sysconfig/slurmd
  ansible.builtin.copy:
    src: etc/sysconfig/slurmd
    dest: /etc/sysconfig/slurmd
    owner: root
    group: root
    mode: '00644'
  register: sdsc

- name: Install prolog/epilog scripts
  ansible.builtin.copy:
    src: files/etc/slurm/scripts/{{ item }} 
    dest: /etc/slurm/scripts
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: '0755'
  loop:
    - prolog.sh
    - taskprolog.sh
    - epilog.sh

- name: start/restart and enable slurmd.service
  ansible.builtin.systemd_service:
    name: slurmd.service
    state: "{{ 'restarted' if sdsc.changed else 'started' }}"
    enabled: yes
    daemon_reload: yes
