- name: install /etc/ssh/ssh_host_{ecdsa,ed25519,rsa}_key{,.pub}
  ansible.builtin.copy:
    content: |
      {{ lookup('env', item.envvar) }}
    dest: "{{ item.file }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ compute_ssh_host_keys }}"
  register: sshkeys

- name: restart sshd.service
  ansible.builtin.systemd_service:
    name: sshd.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: sshkeys.changed
