ood_version: 4.0
ood_rpm: ondemand-release-web-{{ ood_version }}-1.{{ distros[distro]['el'] }}.noarch.rpm
ood_file_upload_max_bytes: 136577024
ood_download_dir_max_bytes: 1073741824

# defined in inventory:
# ood_tier
# ood_domain
# ood_certbot_staging
# ood_dashboard_title
# ood_oidc_client_id
# ood_oidc_client_secret

# there should be one of these for every base directory in
# ood_{files,templates} below
ood_dirs:
  - /etc/ood/config/announcements.d
  - /etc/ood/config/apps/bc_desktop/submit
  - /etc/ood/config/apps/dashboard/initializers
  - /etc/ood/config/apps/dashboard/views/dashboard
  - /etc/ood/config/apps/dashboard/views/layouts/nav
  - /etc/ood/config/apps/dashboard/views/support_ticket/email
  - /etc/ood/config/apps/dashboard/views/batch_connect/sessions/card
  - /etc/ood/config/apps/dashboard/views/widgets/pinned_apps
  - /etc/ood/config/apps/myjobs/app/views/layouts/nav
  - /etc/ood/config/apps/shell
  - /etc/ood/config/clusters.d
  - /etc/ood/config/locales
  - /etc/ood/config/ondemand.d
  - /var/www/ood/apps/sys/dashboard/app/assets/stylesheets
  - /var/www/ood/public/assets/css
  - /var/www/ood/public/assets/images
  - /var/www/ood/public/assets/js
  - /var/www/ood/public/maintenance

# https://osc.github.io/ood-documentation/latest/customizations.html#announcements
# https://osc.github.io/ood-documentation/latest/customizations.html#custom-css-files
# https://osc.github.io/ood-documentation/latest/customizations.html#maintenance-mode
# https://osc.github.io/ood-documentation/latest/customizations.html#pinning-applications-to-the-dashboard

# these should exist in files/ exactly as specified here
ood_files:
  - etc/ood/config/announcements.d/carina_announcement.yml
  - var/www/ood/apps/sys/bc_desktop/icon.png
  - var/www/ood/public/carina-logo-white.png
  - var/www/ood/public/logo.png
  - var/www/ood/public/assets/css/custom.css
  - var/www/ood/public/assets/js/tour.js
  - var/www/ood/public/assets/images/sas.png
  - var/www/ood/public/assets/images/sas-logo.png
  - var/www/ood/public/assets/images/tour-splash.png
  - var/www/ood/public/maintenance/index.html


# these should exist in templates/ with a .j2 extension
ood_templates:
  - etc/httpd/conf.d/mpm_event.conf
  - etc/ood/config/apps/bc_desktop/c2.yml
  - etc/ood/config/apps/bc_desktop/submit/c2.yml.erb
  - etc/ood/config/apps/dashboard/env
  - etc/ood/config/apps/dashboard/initializers/ood.rb
  - etc/ood/config/apps/dashboard/views/batch_connect/sessions/card/_card_body.html.erb
  - etc/ood/config/apps/dashboard/views/batch_connect/sessions/card/_card_head.html.erb
  - etc/ood/config/apps/dashboard/views/batch_connect/sessions/card/_created.html.erb
  - etc/ood/config/apps/dashboard/views/dashboard/index.html.erb
  - etc/ood/config/apps/dashboard/views/dashboard/_sas_box.html.erb
  - etc/ood/config/apps/dashboard/views/layouts/application.html.erb
  - etc/ood/config/apps/dashboard/views/layouts/nav/_brandbar.html.erb
  - etc/ood/config/apps/dashboard/views/layouts/nav/_user.html.erb
  - etc/ood/config/apps/dashboard/views/layouts/_global_footer.html.erb
  - etc/ood/config/apps/dashboard/views/layouts/_google_fonts.erb
  - etc/ood/config/apps/dashboard/views/support_ticket/email/_email.text.erb
  - etc/ood/config/apps/dashboard/views/widgets/pinned_apps/_app.html.erb
  - etc/ood/config/apps/dashboard/views/widgets/_carina_splash.html
  - etc/ood/config/apps/dashboard/views/widgets/_dash_list.html.erb
  - etc/ood/config/apps/dashboard/views/widgets/_pinned_apps.html.erb
  - etc/ood/config/apps/dashboard/views/widgets/_recently_used_apps.html.erb
  - etc/ood/config/apps/dashboard/views/widgets/_sessions.html.erb
  - etc/ood/config/apps/myjobs/app/views/layouts/nav/_styles.html.erb
  - etc/ood/config/apps/shell/env
  - etc/ood/config/clusters.d/c2.yml
  - etc/ood/config/locales/en.yml
  - etc/ood/config/nginx_stage.yml
  - etc/ood/config/ondemand.d/dashboard.yml
  - etc/ood/config/ondemand.d/stanford.yml
  - etc/ood/config/ondemand.d/support_ticket.yml
  - etc/ood/config/ood_portal.yml
  - opt/ood/ood-portal-generator/templates/ood-portal.conf.erb
  - var/www/ood/apps/sys/dashboard/app/assets/stylesheets/_variables.scss

# resolved in template _carina_splash.html
ood_feedback_form_url: https://docs.google.com/forms/d/e/1FAIpQLSc11mS0VmAOGIRcVmz4XDN6a83Q6VlThYkJXUfWGmsYiUnKxg/viewform?usp=header

ood_dev_users:
  - addiso
  - btempero
  - ddh
  - gancayco
  - mpiercy
  - mvan
  - rvrollin
  - saracook

apache_tls_key: /etc/pki/tls/private/{{ ood_domain }}.pem
apache_tls_crt: /etc/pki/tls/certs/{{ ood_domain }}.pem
apache_webroot: /var/www/html

certbot_email: srcc-support@stanford.edu
certbot_tls_key: /etc/letsencrypt/live/{{ ood_domain }}/privkey.pem
certbot_tls_crt: /etc/letsencrypt/live/{{ ood_domain }}/fullchain.pem
certbot_plugin_venv: /opt/certbot-plugin-venv
certbot_dns_google_plugin_package: certbot-dns-google
certbot_dns_google_project: srcc-anthos-secure-prod
certbot_dns_google_credentials_file: /dev/shm/certbot-dns-google-credentials.json
certbot_dns_google_credentials_json: "{{ lookup('env','OOD_CERTBOT_DNS_GOOGLE_CREDENTIALS_JSON_B64') | b64decode }}"
certbot_dns_google_propagation_seconds: 60

ood_jupyterlab_venv: /software/environments/ood-jupyterlab

# todo: this is also defined in role c2-rpm-repo-server
code_server_version: '4.104.3'
