[default]
host = {{ inventory_hostname }}.{{ domain }}
index = {{ splunk_client_index }}

[monitor:///var/ossec/logs/alerts/alerts.log]
disabled=0
sourcetype=ossec_alerts

[monitor:///var/ossec/logs/ossec.log]
disabled=0
sourcetype=ossec_log

[monitor:///var/ossec/logs/active-responses.log]
disabled=0
sourcetype=ossec_ar
