[default]
host = {{ inventory_hostname }}.{{ domain }}
index = {{ splunk_client_index }}

[monitor:///var/log/audit/audit.log]
disabled = 0
sourcetype = linux_audit

[monitor:///var/log/messages]
disabled = 0
sourcetype = linux_messages_syslog

[monitor:///var/log/secure]
disabled = 0
sourcetype = linux_secure

[monitor:///var/ossec/logs/alerts/alerts.log]
disabled = 0
sourcetype = ossec_alerts

[monitor:///var/ossec/logs/ossec.log]
disabled = 0
sourcetype = ossec_log

[monitor:///var/ossec/logs/active-responses.log]
disabled = 0
sourcetype = ossec_ar
