[sslConfig]
serverCert = /opt/splunkforwarder/etc/auth/su-certs/susplunkforwarder.pem
sslPassword = {{ splunk_client_tls_key_passphrase }}
sslRootCAPath = /opt/splunkforwarder/etc/auth/su-certs/susplunkrootca.pem
