apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: carina-prod
  name: user-mgmt-db
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 25G
  persistentVolumeReclaimPolicy: Retain
  rbd:
    fsType: ext4
    image: user-mgmt-db
    keyring: /etc/ceph/keyring
    monitors:
    - 192.168.2.17
    - 192.168.2.26
    - 192.168.2.6
    pool: nvme-rbd
    secretRef:
      name: rbd-keyring
      namespace: ceph-rbd
    user: kubernetes-rbd-provisioner
  volumeMode: Filesystem
