- name: install grafana package
  ansible.builtin.dnf:
    name: grafana-{{ grafana_version }}
    state: present
    update_cache: yes
    enablerepo: grafana

# todo: manage /etc/sysconfig/grafana-server and /etc/grafana/grafana.ini

- name: start/enable grafana-server.service
  ansible.builtin.systemd_service:
    name: grafana-server.service
    state: started
    enabled: yes
    daemon_reload: yes
