- name: create directory /etc/opt/BESClient
  ansible.builtin.file:
    path: /etc/opt/BESClient
    state: directory

- name: create directory /var/opt/BESClient
  ansible.builtin.file:
    path: /var/opt/BESClient
    state: directory

- name: download actionsite config file
  ansible.builtin.get_url:
    url: "{{ actionsite_url }}"
    dest: /etc/opt/BESClient/actionsite.afxm
    checksum: sha256:{{ actionsite_sha256 }}

- name: install /var/opt/BESClient/besclient.config
  ansible.builtin.template:
    src: var/opt/BESClient/besclient.config
    dest: /var/opt/BESClient/besclient.config

- name: install package libcurl4 (depends on libssl3)
  ansible.builtin.apt:
    name: libcurl4
    state: present
    update_cache: yes

- name: download agent deb package
  ansible.builtin.get_url:
    url: "{{ agent_deb_url }}"
    dest: /var/tmp/{{ agent_deb_url | basename }}
    checksum: sha256:{{ agent_deb_sha256 }}

- name: install agent deb package
  ansible.builtin.apt:
    deb: /var/tmp/{{ agent_deb_url | basename }}
    state: present

- name: start and enable besclient service
  ansible.builtin.systemd_service:
    name: besclient.service
    state: started
    enabled: yes
    daemon_reload: yes
