- name: >
    check for client and root ca certificates
    (see role c2-splunk-client-certificate)
  delegate_to: localhost
  become: no
  run_once: yes
  block:

    - name: stat {{ splunk_client_tls_crt }}
      ansible.builtin.stat:
        path: "{{ splunk_client_tls_crt }}"
      register: splkclitlscrt

    - name: fail if {{ splunk_client_tls_crt }} doesn't exist
      ansible.builtin.fail:
      when: not splkclitlscrt.stat.exists

    - name: stat {{ splunk_rootca_tls_crt }}
      ansible.builtin.stat:
        path: "{{ splunk_rootca_tls_crt }}"
      register: splkrtcatlscrt

    - name: fail if {{ splunk_rootca_tls_crt }} doesn't exist
      ansible.builtin.fail:
      when: not splkrtcatlscrt.stat.exists

# nb: rpm is installed in c2-local repo in role c2-rpm-repo-server
- name: install splunkforwarder package
  ansible.builtin.dnf:
    name: splunkforwarder-9.1.2
    state: present
    update_cache: yes
    enablerepo: c2-local

# todo:
# replace deprecated CPUShares with CPUWeight
# replace deprecated MemoryLimit with MemoryMax
- name: install /etc/systemd/system/SplunkForwarder.service
  ansible.builtin.command:
    cmd: >
      /opt/splunkforwarder/bin/splunk enable
      --accept-license
      --answer-yes
      --no-prompt
      --seed-passwd "$SPLUNK_CLIENT_ADMIN_PASSWORD"
      boot-start
    creates: /etc/systemd/system/SplunkForwarder.service
  environment:
    SPLUNK_CLIENT_ADMIN_PASSWORD: "{{ splunk_client_admin_password }}"

- name: create directory /opt/splunkforwarder/etc/auth/su-certs
  ansible.builtin.file:
    path: /opt/splunkforwarder/etc/auth/su-certs
    state: directory
    owner: splunkfwd
    group: splunkfwd
    mode: '00700'

- name: install /opt/splunkforwarder/etc/auth/su-certs/susplunkforwarder.pem
  ansible.builtin.template:
    src: opt/splunkforwarder/etc/auth/su-certs/susplunkforwarder.pem
    dest: /opt/splunkforwarder/etc/auth/su-certs/susplunkforwarder.pem
    owner: splunkfwd
    group: splunkfwd
    mode: '00644'
  register: splclicrt

- name: install /opt/splunkforwarder/etc/auth/su-certs/susplunkrootca.pem
  ansible.builtin.template:
    src: opt/splunkforwarder/etc/auth/su-certs/susplunkrootca.pem
    dest: /opt/splunkforwarder/etc/auth/su-certs/susplunkrootca.pem
    owner: splunkfwd
    group: splunkfwd
    mode: '00644'
  register: splrtcacrt

- name: install /opt/splunkforwarder/etc/system/local/deploymentclient.conf
  ansible.builtin.template:
    src: opt/splunkforwarder/etc/system/local/deploymentclient.conf
    dest: /opt/splunkforwarder/etc/system/local/deploymentclient.conf
    owner: splunkfwd
    group: splunkfwd
    mode: '00644'
  register: spldplcli

- name: install /opt/splunkforwarder/etc/system/local/inputs.conf
  ansible.builtin.template:
    src: opt/splunkforwarder/etc/system/local/inputs.conf
    dest: /opt/splunkforwarder/etc/system/local/inputs.conf
    owner: splunkfwd
    group: splunkfwd
    mode: '00644'
  register: spllclinp

- name: install /opt/splunkforwarder/etc/system/local/outputs.conf
  ansible.builtin.template:
    src: opt/splunkforwarder/etc/system/local/outputs.conf
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf
    owner: splunkfwd
    group: splunkfwd
    mode: '00600'
  register: spllclotp

- name: install /opt/splunkforwarder/etc/system/local/server.conf
  ansible.builtin.template:
    src: opt/splunkforwarder/etc/system/local/server.conf
    dest: /opt/splunkforwarder/etc/system/local/server.conf
    owner: splunkfwd
    group: splunkfwd
    mode: '00600'
  register: spllclsrvcf

# todo: set PYTHONHTTPSVERIFY=1 in /opt/splunkforwarder/etc/splunk-launch.conf

- name: enable and start/restart SplunkForwarder.service
  ansible.builtin.systemd_service:
    name: SplunkForwarder.service
    enabled: yes
    state: "{{ 'restarted' if splclicrt.changed or splrtcacrt.changed or spldplcli.changed or spllclinp.changed or spllclotp.changed or spllclsrvcf.changed else 'started' }}"
    daemon_reload: yes
