# ./users/cyouh95/kustomization.yaml
namespace: cyouh95

resources:
- ../../base/user
- ../../base/configmaps


patches:
- target:
    kind: Namespace
    name: default
  patch: |-
    - op: replace
      path: /metadata/name
      value: cyouh95
- target:
    kind: PersistentVolume
    name: cephfs-static-home
  patch: |-
    - op: replace
      path: /metadata/name
      value: cephfs-static-home-cyouh95
    - op: replace
      path: /spec/csi/volumeHandle
      value: cephfs-static-home-cyouh95
- target:
    kind: PersistentVolume
    name: cephfs-static-pi
  patch: |-
    - op: replace
      path: /metadata/name
      value: cephfs-static-pi-cyouh95
    - op: replace
      path: /spec/csi/volumeHandle
      value: cephfs-static-pi-cyouh95
- target:
    kind: PersistentVolumeClaim
    name: cephfs-static-home
  patch: |-
    - op: replace
      path: /spec/volumeName
      value: cephfs-static-home-cyouh95
- target:
    kind: PersistentVolumeClaim
    name: cephfs-static-pi
  patch: |-
    - op: replace
      path: /spec/volumeName
      value: cephfs-static-pi-cyouh95
- target:
    kind: Service
    name: jupyter
  patch: |-
    - op: replace
      path: /spec/selector/hub.jupyter.org~1username
      value: cyouh95
