- name: create xfs filesystem on /dev/{{ data_disk_dev }}
  community.general.filesystem:
    dev: /dev/{{ data_disk_dev }}
    fstype: xfs

- name: run blkid to get xfs filesystem uuid of /dev/{{ data_disk_dev }}
  ansible.builtin.command:
    cmd: blkid -o value -s UUID /dev/{{ data_disk_dev }}
  register: uuid
  changed_when: false

- name: mount /dev/{{ data_disk_dev }} on /srv
  ansible.posix.mount:
    src: UUID={{ uuid.stdout }}
    path: /srv
    fstype: xfs
    opts: defaults
    state: mounted
