apiVersion: v1
kind: ConfigMap
metadata:
  name: extrausers
data:
  addgroup.sh: "#!/bin/bash\n#script to run inside docker and create users\nset -e
    \     # stop on error\nset -u      # stop on uninitialized variable\n\n#   @input
    \     $1: user name\n#               $2: uid\n#               $3: PI gid\n#\t\t$4
    GECOS info\n#   @return     success (0) / failure (1)\n#\n\ngroupname=$1\n#cp
    /var/lib/extrausers/group /etc\n#cp /var/lib/extrausers/group- /etc\n#cp /var/lib/extrausers/gshadow
    /etc\n#cp /var/lib/extrausers/gshadow- /etc\naddgroup --extrausers --conf /var/lib/extrausers/group-add-user.conf
    $groupname 2> /dev/null\n#cp /etc/group /var/lib/extrausers\n#cp /etc/group- /var/lib/extrausers\n#cp
    /etc/gshadow /var/lib/extrausers\n#cp /etc/gshadow- /var/lib/extrauser\n"
  addpi.sh-deprecated: "#!/bin/bash\n#script to run inside docker and create users\nset
    -e      # stop on error\nset -u      # stop on uninitialized variable\n\n#   @input
    \     $1: user name\n#               $2: uid\n#               $3: PI gid\n#\t\t$4
    GECOS info\n#   @return     success (0) / failure (1)\n#\n\ngroupname=$1\ncp /var/lib/extrausers/group
    /etc\ncp /var/lib/extrausers/group- /etc\ncp /var/lib/extrausers/gshadow /etc\ncp
    /var/lib/extrausers/gshadow- /etc\ngroupadd $groupname\ncp /etc/group /var/lib/extrausers\ncp
    /etc/group- /var/lib/extrausers\ncp /etc/gshadow /var/lib/extrausers\ncp /etc/gshadow-
    /var/lib/extrausers\n"
  adduser.conf: |
    # /etc/adduser.conf: `adduser' configuration.
    # See adduser(8) and adduser.conf(5) for full documentation.

    # The DSHELL variable specifies the default login shell on your
    # system.
    DSHELL=/bin/bash

    # The DHOME variable specifies the directory containing users' home
    # directories.
    DHOME=/home

    # If GROUPHOMES is "yes", then the home directories will be created as
    # /home/groupname/user.
    GROUPHOMES=no

    # If LETTERHOMES is "yes", then the created home directories will have
    # an extra directory - the first letter of the user name. For example:
    # /home/u/user.
    LETTERHOMES=no

    # The SKEL variable specifies the directory containing "skeletal" user
    # files; in other words, files such as a sample .profile that will be
    # copied to the new user's home directory when it is created.
    SKEL=/etc/skel

    # FIRST_SYSTEM_[GU]ID to LAST_SYSTEM_[GU]ID inclusive is the range for UIDs
    # for dynamically allocated administrative and system accounts/groups.
    # Please note that system software, such as the users allocated by the base-passwd
    # package, may assume that UIDs less than 100 are unallocated.
    FIRST_SYSTEM_UID=100
    LAST_SYSTEM_UID=999

    FIRST_SYSTEM_GID=100
    LAST_SYSTEM_GID=999

    # FIRST_[GU]ID to LAST_[GU]ID inclusive is the range of UIDs of dynamically
    # allocated user accounts/groups.
    FIRST_UID=1000
    LAST_UID=59999

    FIRST_GID=1000
    LAST_GID=59999

    # The USERGROUPS variable can be either "yes" or "no".  If "yes" each
    # created user will be given their own group to use as a default.  If
    # "no", each created user will be placed in the group whose gid is
    # USERS_GID (see below).
    USERGROUPS=yes

    # If USERGROUPS is "no", then USERS_GID should be the GID of the group
    # `users' (or the equivalent group) on your system.
    USERS_GID=100

    # If DIR_MODE is set, directories will be created with the specified
    # mode. Otherwise the default mode 0755 will be used.
    DIR_MODE=0755

    # If SETGID_HOME is "yes" home directories for users with their own
    # group the setgid bit will be set. This was the default for
    # versions << 3.13 of adduser. Because it has some bad side effects we
    # no longer do this per default. If you want it nevertheless you can
    # still set it here.
    SETGID_HOME=no

    # If QUOTAUSER is set, a default quota will be set from that user with
    # `edquota -p QUOTAUSER newuser'
    QUOTAUSER=""

    # If SKEL_IGNORE_REGEX is set, adduser will ignore files matching this
    # regular expression when creating a new home directory
    SKEL_IGNORE_REGEX="dpkg-(old|new|dist|save)"

    # Set this if you want the --add_extra_groups option to adduser to add
    # new users to other groups.
    # This is the list of groups that new non-system users will be added to
    # Default:
    EXTRA_GROUPS="carina_users"

    # If ADD_EXTRA_GROUPS is set to something non-zero, the EXTRA_GROUPS
    # option above will be default behavior for adding new, non-system users
    ADD_EXTRA_GROUPS=1


    # check user and group names also against this regular expression.
    #NAME_REGEX="^[a-z][-a-z0-9_]*\$"

    # use extrausers by default
    USE_EXTRAUSERS=1
  adduser.sh: "#!/bin/bash\n#script to run inside docker and create users\n#set -e
    \     # stop on error\n#set -u      # stop on uninitialized variable\n\n#   @input
    \     $1: user name\n#               $2: uid\n#               $3: PI gid\n#\t\t$4
    GECOS info\n#   @return     success (0) / failure (1)\n#\n\nusrname=$1\nuid=$2\ngid=$3\ngecos=\"$4\"\n\n\ngroupadd
    --extrausers -g $uid $usrname 2>/dev/null\nadduser --disabled-password --extrausers
    --no-create-home --shell /bin/bash --quiet --uid $uid --gid $uid --gecos \"$gecos\"
    $usrname 2>/dev/null\ncp /etc/group /root\ncp /etc/group- /root\ncp /etc/gshadow
    /root\ncp /etc/gshadow- /root\ncp /var/lib/extrausers/group /etc\ncp /var/lib/extrausers/group-
    /etc\ncp /var/lib/extrausers/gshadow /etc\ncp /var/lib/extrausers/gshadow- /etc\n##add
    to supplementary groups\necho adding pi group $gid\nadduser --extrausers --conf
    /var/lib/extrausers/group-add-user.conf $usrname $gid\nadduser --extrausers --conf
    /var/lib/extrausers/group-add-user.conf $usrname carina_users\ncp /etc/group /var/lib/extrausers\ncp
    /etc/group- /var/lib/extrausers\ncp /etc/gshadow /var/lib/extrausers\ncp /etc/gshadow-
    /var/lib/extrausers\ncp /root/gshadow /etc\ncp /root/gshadow- /etc\ncp /root/group
    /etc\ncp /root/group- /etc\n#echo \"copied group info back\"\nexit 0\n"
