apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gsm-store
spec:
  provider:
      gcpsm:                                  # gcpsm provider
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcp-creds              # secret name containing SA key
              key: secret-access-credentials  # key name containing SA key
              namespace: external-secrets
        projectID: srcc-anthos-secure-prod        # name of Google Cloud project
