# obtain the proot release binary (e.g. v5.3.1):
# proceed to pipelines:
# https://gitlab.com/proot/proot/-/pipelines
# click on pipeline corresponding to tagged release:
# https://gitlab.com/proot/proot/-/pipelines/523440826
# click on "dist" job:
# https://gitlab.com/proot/proot/-/jobs/2370229659
# click on "browse" in right panel:
# https://gitlab.com/proot/proot/-/jobs/2370229659/artifacts/browse
# click on "dist" directory:
# https://gitlab.com/proot/proot/-/jobs/2370229659/artifacts/browse/dist/
# click on file "proot":
# https://gitlab.com/proot/proot/-/jobs/2370229659/artifacts/file/dist/proot
# click on "download" link:
# https://gitlab.com/proot/proot/-/jobs/2370229659/artifacts/raw/dist/proot
# click on file "proot.sha256sum":
# https://gitlab.com/proot/proot/-/jobs/2370229659/artifacts/file/dist/proot.sha256sum
# click on "download" link:
# https://gitlab.com/proot/proot/-/jobs/2370229659/artifacts/raw/dist/proot.sha256sum
proot_binary_url: https://gitlab.com/proot/proot/-/jobs/2370229659/artifacts/raw/dist/proot
proot_binary_sha256: b7f2adf5a225000a164f4905aabefeebe11c4c1d5bedff5e1fe8866c48dd70d2


### defaults for disk-config task ###
local_dir: "/local/scratch"
