compute_ssh_host_keys:
  - envvar: COMPUTE_NODE_SSH_ECDSA_PRIVATE_KEY
    file: /etc/ssh/ssh_host_ecdsa_key
    owner: root
    group: ssh_keys
    mode: '00640'
  - envvar: COMPUTE_NODE_SSH_ECDSA_PUBLIC_KEY
    file: /etc/ssh/ssh_host_ecdsa_key.pub
    owner: root
    group: root
    mode: '00644'
  - envvar: COMPUTE_NODE_SSH_ED25519_PRIVATE_KEY
    file: /etc/ssh/ssh_host_ed25519_key
    owner: root
    group: ssh_keys
    mode: '00640'
  - envvar: COMPUTE_NODE_SSH_ED25519_PUBLIC_KEY
    file: /etc/ssh/ssh_host_ed25519_key.pub
    owner: root
    group: root
    mode: '00644'
  - envvar: COMPUTE_NODE_SSH_RSA_PRIVATE_KEY
    file: /etc/ssh/ssh_host_rsa_key
    owner: root
    group: ssh_keys
    mode: '00640'
  - envvar: COMPUTE_NODE_SSH_RSA_PUBLIC_KEY
    file: /etc/ssh/ssh_host_rsa_key.pub
    owner: root
    group: root
    mode: '00644'

# obtain the proot release binary (e.g. v5.3.1):
# proceed to pipelines:
# https://gitlab.com/proot/proot/-/pipelines
# click on pipeline corresponding to tagged release:
# https://gitlab.com/proot/proot/-/pipelines/523440826
# click on "dist" job:
# https://gitlab.com/proot/proot/-/jobs/2370229659
# click on "browse" in right panel:
# https://gitlab.com/proot/proot/-/jobs/2370229659/artifacts/browse
# click on "dist" directory:
# https://gitlab.com/proot/proot/-/jobs/2370229659/artifacts/browse/dist/
# click on file "proot":
# https://gitlab.com/proot/proot/-/jobs/2370229659/artifacts/file/dist/proot
# click on "download" link:
# https://gitlab.com/proot/proot/-/jobs/2370229659/artifacts/raw/dist/proot
# click on file "proot.sha256sum":
# https://gitlab.com/proot/proot/-/jobs/2370229659/artifacts/file/dist/proot.sha256sum
# click on "download" link:
# https://gitlab.com/proot/proot/-/jobs/2370229659/artifacts/raw/dist/proot.sha256sum
proot_binary_url: https://gitlab.com/proot/proot/-/jobs/2370229659/artifacts/raw/dist/proot
proot_binary_sha256: b7f2adf5a225000a164f4905aabefeebe11c4c1d5bedff5e1fe8866c48dd70d2

local_scratch_dev: /dev/md0
local_scratch_dir: /local/scratch
