apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  name: cephfs-static-home-CHANGEME
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 305T
  claimRef:
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: csi-cephfs-home-client-secret
      namespace: cephfs
    volumeAttributes:
      clusterID: cc06bc72-cacd-11eb-8bdd-97416ba6ca5f
      fsName: gp-fs
      rootPath: /volumes/stanford/home/dfc1195b-889d-4123-9a99-c223bb9cc830
      staticVolume: "true"
    volumeHandle: cephfs-static-home-CHANGEME
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
