apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: BackupStorageLocation
  metadata:
    labels:
      component: velero
    name: default
    namespace: velero
  spec:
    default: true
    objectStorage:
      bucket: velero-default
    provider: gcp
- apiVersion: velero.io/v1
  kind: VolumeSnapshotLocation
  metadata:
    labels:
      component: velero
    name: default
    namespace: velero
  spec:
    provider: gcp
kind: List
