apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: cephfs-static-home
  #namespace: CHANGEME
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 305T
  volumeMode: Filesystem
  volumeName: cephfs-static-home-CHANGEME
