apiVersion: v1
data:
  acct_gather.conf: |
    #EnergyIPMIFrequency=30
    #EnergyIPMICalcAdjustment=yes
  allowed_devices.conf: |
    /dev/null
    /dev/urandom
    /dev/zero
    /dev/sda*
    /dev/cpu/*/*
    /dev/pts/*
    /dev/tty*
  cgroup.conf: |
    # general
    CgroupAutomount=yes

    # task/cgroup plugin
    TaskAffinity=yes        # require hwloc
    ConstrainCores=yes
    ConstrainRAMSpace=yes
    ConstrainSwapSpace=yes
    ConstrainKmemSpace=no

    # prevent jobs from using swap space
    AllowedRAMSpace=100     # in %
    AllowedSwapSpace=0      # in %
    MinRAMSpace=30

    # constraint devices    # prevent using non-allocated gres devices
    ConstrainDevices=yes
    AllowedDevicesFile=/etc/slurm/allowed_devices.conf
  gres.conf: |
    #
    # 2 GPUs nodes - seems not to work with processor affinity
    #

    # NB: CORE ids are _logical_ core ids, as reported w/ lstopo -l

    # 32c - 4x PCI GPUs
    Nodename=secure-gpu-[1,2] name=gpu    file=/dev/nvidia0 COREs=0-15
    Nodename=secure-gpu-[1,2] name=gpu    file=/dev/nvidia1 COREs=16-31
    Nodename=secure-gpu-[3-8] name=gpu    file=/dev/nvidia0 COREs=0-19
    Nodename=secure-gpu-[3-8] name=gpu    file=/dev/nvidia1 COREs=0-19
    Nodename=secure-gpu-[3-8] name=gpu    file=/dev/nvidia2 COREs=0-19
    Nodename=secure-gpu-[3-8] name=gpu    file=/dev/nvidia3 COREs=0-19
  slurm.conf: |
    ClusterName=secure
    ControlMachine=slurmcontroller
    ControlAddr=10.152.183.156
    SlurmUser=slurm
    SlurmctldPort=6817
    SlurmdPort=6818
    AuthType=auth/munge
    StateSaveLocation=/var/lib/slurmd
    SlurmdSpoolDir=/var/spool/slurmd
    SwitchType=switch/none
    SlurmctldPidFile=/var/run/slurmd/slurmctld.pid
    SlurmdPidFile=/var/run/slurmd/slurmd.pid
    MailDomain=stanford.edu
    #MailProg=/usr/bin/s-nail

    #tracking and plugins
    ProctrackType=proctrack/cgroup
    TaskPlugin=task/cgroup
    TopologyPlugin=topology/tree

    # MPI
    #
    MpiDefault=pmi2

    # Resources and limits
    #
    MinJobAge=10
    MaxJobCount=50000
    GresTypes=gpu
    PropagateResourceLimitsExcept=MEMLOCK,NOFILE,NPROC,AS,CPU
    PrivateData=reservations,usage,users,accounts

    CacheGroups=0
    ReturnToService=1
    ResumeProgram=true
    SlurmctldTimeout=300
    SlurmdTimeout=300
    InactiveLimit=0
    KillWait=30
    Waittime=0

    #Scheduling
    #
    SchedulerType=sched/backfill
    SelectType=select/cons_res
    SelectTypeParameters=CR_Core_Memory
    FastSchedule=1
    SchedulerParameters=default_queue_depth=5000,partition_job_depth=2000,bf_continue,bf_yield_interval=1000000,bf_yield_sleep=750000,bf_busy_nodes,bf_interval=120,bf_max_time=240,bf_window=10080,bf_job_part_count_reserve=10,bf_max_job_test=10000,bf_max_job_array_resv=10,bf_max_job_user_part=100,bf_resolution=1800,bf_min_prio_reserve=3000,kill_invalid_depend,nohold_on_prolog_fail,pack_serial_at_end,preempt_youngest_first,reduce_completing_frag,batch_sched_delay=20,sched_min_interval=1000000,build_queue_timeout=5000000,jobs_per_user_per_hour=2000,max_rpc_cnt=256

    # FairShare
    #
    PriorityType=priority/multifactor
    PriorityDecayHalfLife=7-0
    PriorityMaxAge=14-0
    PriorityWeightAge=1000
    PriorityWeightFairshare=10000
    PriorityWeightJobSize=50000000
    PriorityWeightPartition=10000
    PriorityWeightQOS=1000000
    PriorityWeightTRES=CPU=5000,Mem=10000,GRES/gpu=25000
    PriorityFlags=SMALL_RELATIVE_TO_TIME,FAIR_TREE,CALCULATE_RUNNING
    FairShareDampeningFactor=5

    # Preemption
    #
    PreemptMode=requeue
    PreemptType=preempt/partition_prio

    SlurmctldDebug=3
    SlurmctldLogFile=/var/log/slurm/slurmctld.log
    SlurmdDebug=3
    SlurmdLogFile=/var/log/slurm/slurmd.log

    #Accounting
    #
    JobCompType=jobcomp/none
    JobCompLoc=/var/log/slurm/jobcomp.log
    JobAcctGatherType=jobacct_gather/cgroup
    JobAcctGatherFrequency=30
    AccountingStorageType=accounting_storage/slurmdbd
    JobAcctGatherParams=UsePss
    AccountingStorageEnforce=QOS,limits,safe
    AccountingStorageTRES=gres/gpu
    EnforcePartLimits=ANY
    AcctGatherNodeFreq=300
    AccountingStorageHost=slurmcontroller
    AccountingStoragePort=6819
    AccountingStorageLoc=slurm_acct_db

    #Node and Partition Descriptions
    #
    NodeName=secure-[1-16] RealMemory=370000 SocketsPerBoard=2 CoresPerSocket=16 ThreadsPerCore=1  Feature="CPU_GEN:SKX,CPU_SKU:6130,CPU_FRQ:2.10GHz,CLOUD" State=CLOUD
    NodeName=secure-gpu-[1-2] Gres=gpu:2 RealMemory=370000 SocketsPerBoard=2 CoresPerSocket=16 ThreadsPerCore=1  Feature="CPU_GEN:SKX,CPU_SKU:6130,CPU_FRQ:2.10GHz,GPU_GEN:PSC,GPU_BRD:TESLA,GPU_SKU:P100_PCIE,GPU_MEM:16GB,GPU_CC:6.0,CLOUD" State=CLOUD
    NodeName=secure-gpu-[3-8] Gres=gpu:4 RealMemory=250000 SocketsPerBoard=2 CoresPerSocket=10 ThreadsPerCore=1 Feature="CPU_GEN:SKX,CPU_SKU:4114,CPU_FRQ:2.2GHz,GPU_GEN:PSC,GPU_BRD:TESLA,GPU_SKU:V100_PCIE,GPU_MEM:32GB,GPU_CC:7.0,CLOUD" State=CLOUD
    PartitionName=normal Default=yes Nodes=secure-[1-4] Priority=50 DefMemPerCPU=500 Shared=NO MaxNodes=2 MaxTime=2-00:00:00 DefaultTime=0-02:00:00
    PartitionName=gpu Nodes=secure-gpu-[1-8] Priority=50 DefMemPerCPU=500 Shared=NO MaxNodes=3 MaxTime=2-00:00:00 DefaultTime=0-02:00:00
  topology.conf: |
    #
    # Ethernet network topology for secure

    SwitchName=secure-sw Nodes=secure-gpu-[1-8],secure-[1-16]
kind: ConfigMap
metadata:
  name: slurm-node-conf
