- name: delegate to localhost
  delegate_to: localhost
  become: no
  run_once: yes
  block:

    - name: create directory {{ splunk_client_tls_crt | dirname }}
      ansible.builtin.file:
        path: "{{ splunk_client_tls_crt | dirname }}"
        state: directory
    
    - name: install {{ splunk_client_tls_cfg }}
      ansible.builtin.template:
        src: "{{ splunk_client_tls_cfg_tmpl }}"
        dest: "{{ splunk_client_tls_cfg }}"
    
    - name: generate {{ splunk_client_tls_key }} and {{ splunk_client_tls_csr }}
      ansible.builtin.shell:
        cmd: >
          openssl req
          -new
          -nodes
          -newkey rsa:2048
          -keyout {{ splunk_client_tls_key }}
          -passout pass:"{{ splunk_client_tls_key_passphrase }}"
          -out {{ splunk_client_tls_csr }}
          -config {{ splunk_client_tls_cfg }}
        creates: "{{ splunk_client_tls_csr }}"
    
    - name: print file locations
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - "{{ splunk_client_tls_cfg }}"
        - "{{ splunk_client_tls_key }}"
        - "{{ splunk_client_tls_csr }}"
    
    - name: print further instructions
      ansible.builtin.debug:
        msg: |
          TODO:
          1) Upload {{ splunk_client_tls_csr }} to
             https://susplunk.stanford.edu/signcert
          2) Download cert file to {{ splunk_client_tls_crt }}
          3) Download root ca file to {{ splunk_rootca_tls_crt }}
          4) Run playbook c2-base-os.yml
             (or any playbook that depends on role c2-base-os)
