- name: install krb5 packages
  ansible.builtin.dnf:
    name: "{{ krb5_packages }}"
    state: present
    update_cache: yes
    enablerepo: epel

- name: install stanford /etc/krb5.conf
  ansible.builtin.get_url:
    url: "{{ krb5_conf_url }}"
    dest: /etc/krb5.conf
    checksum: "sha256:{{ krb5_conf_sha256 }}"

- name: check for existing host keytab
  ansible.builtin.stat:
    path: /etc/krb5.keytab
  register: keytab

# nb: run this only if /etc/krb5.keytab doesn't exist since keytab
#     is regenerated every time it's retrieved via wallet.
- name: install host keytab
  ansible.builtin.copy:
    content: "{{ lookup('pipe', 'wallet -s wallet.stanford.edu get keytab host/' ~ canonical_hostname ~ ' | base64') | b64decode }}"
    dest: /etc/krb5.keytab
    owner: root
    group: root
    mode: '00600'
  when: not keytab.stat.exists
