- ansible.builtin.include_tasks:
    file: kerberos.yml
    apply:
      tags:
        - kerberos
  tags:
    - always

- ansible.builtin.include_tasks:
    file: sssd.yml
    apply:
      tags:
        - sssd
  tags:
    - always

- ansible.builtin.include_tasks:
    file: duo.yml
    apply:
      tags:
        - duo
  tags:
    - always

- ansible.builtin.include_tasks:
    file: pam.yml
    apply:
      tags:
        - pam
  tags:
    - always

- ansible.builtin.include_tasks:
    file: sshd.yml
    apply:
      tags:
        - sshd
  tags:
    - always
