- name: install sssd packages
  ansible.builtin.dnf:
    name: "{{ sssd_packages }}"
    state: present
    update_cache: yes

# todo: check if this is needed
#- name: disable sssd-sudo activation socket
#  ansible.builtin.systemd_service:
#    name: sssd-sudo.socket
#    state: stopped
#    enabled: no

# todo: use domain global var
- name: install /etc/sssd/sssd.conf
  ansible.builtin.template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: "{{ 'root' if distros[distro]['el'] == 'el9' else 'sssd' }}"
    mode: "{{ '00600' if distros[distro]['el'] == 'el9' else '00640' }}"
  register: sssdconf

- name: start/restart and enable sssd.service
  ansible.builtin.systemd_service:
    name: sssd.service
    state: "{{ 'restarted' if sssdconf.changed else 'started' }}"
    enabled: yes
    daemon_reload: yes

# nb: this is idempotent and we're not modifying any profile files
#     in /etc/authselect that are symlinked in /etc/pam.d .
- name: select authselect profile sssd
  ansible.builtin.command:
    cmd: authselect select --force sssd
  changed_when: false
