---
- name: install /etc/sudoers.d/admins
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "/etc/sudoers.d/{{ item.file }}"
    owner: root
    group: root
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s
  loop:
    - file: admins
      content: |
        %carina_admins ALL=(ALL) ALL
