- name: Install Prometheus Juju Exporter snap
  snap:
    name: prometheus-juju-exporter
    channel: "{{snap_channel}}"
    state: latest

- name: Create systemd service file
  copy:
    dest: /etc/systemd/system/prometheus-juju-exporter.service
    content: |
      [Unit]
      Description=Prometheus Juju Exporter
      After=network.target

      [Service]
      ExecStart=/snap/bin/prometheus-juju-exporter
      Restart=always
      User=nobody
      Group=nogroup

      [Install]
      WantedBy=multi-user.target

- name: Enable and start Prometheus Juju Exporter service
  ansible.builtin.systemd_service:
    name: prometheus-juju-exporter
    daemon_reload: true
    state: started
    enabled: true
