- ansible.builtin.include_tasks:
    file: mariadb.yml
    apply:
      tags:
        - mariadb
  tags:
    - always

- ansible.builtin.include_tasks:
    file: slurmdbd.yml
    apply:
      tags:
        - slurmdbd
  tags:
    - always
