- name: install mariadb packages
  ansible.builtin.dnf:
    name: "{{ mariadb_packages }}"
    state: present
    update_cache: yes
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL

- name: start/enable mariadb.service
  ansible.builtin.systemd_service:
    name: mariadb.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: set root password
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    host: localhost
    name: root
    password: "{{ slurm_db_root_password }}"
    state: present

- name: install /root/.my.cnf
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'

- name: install /home/{{ default_user }}/.my.cnf (root db user)
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /home/{{ default_user }}/.my.cnf
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0600'

- name: create slurm database
  community.mysql.mysql_db:
    name: slurm
    state: present

- name: create slurm user (ip access)
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    host: "{{ '127.0.0.1' if item == 'localhost' else hostvars[item]['ansible_host'] }}"
    name: slurm
    password: "{{ slurm_db_slurm_password }}"
    priv: "slurm.*:ALL"
    state: present
  loop: "{{ ['localhost', inventory_hostname] + groups['c2_slurm_controller'] + groups['c2_login_node'] }}"

- name: create slurm user (hostname access)
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    host: "{{ item }}"
    name: slurm
    password: "{{ slurm_db_slurm_password }}"
    priv: "slurm.*:ALL"
    state: present
  loop: "{{ ['localhost', inventory_hostname] + groups['c2_slurm_controller'] + groups['c2_login_node'] }}"

- name: install /etc/my.cnf.d/mariadb-server.cnf
  ansible.builtin.template:
    src: mariadb-server.cnf.j2
    dest: /etc/my.cnf.d/mariadb-server.cnf
    owner: root
    group: root
    mode: '0644'
  register: mdbscnf

- name: restart mariadb.service
  ansible.builtin.systemd_service:
    name: mariadb.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: mdbscnf is changed
