#per https://istio.io/latest/docs/tasks/observability/logs/access-log/#enable-envoy-s-access-logging
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  accessLogging:
    - providers:
      - name: envoy
...
