- name: install /etc/chrony.conf
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  register: chronyconf

- name: restart chronyd.service
  ansible.builtin.systemd_service:
    name: chronyd.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: chronyconf is changed
