- name: install lmod package
  ansible.builtin.dnf:
    name: Lmod
    state: present
    update_cache: yes
    enablerepo: epel

- name: create directory {{ lmod_modulepath }}
  ansible.builtin.file:
    path: "{{ lmod_modulepath }}"
    state: directory
    owner: root
    group: root
    mode: '00755'

- name: configure lmod modulepath
  ansible.builtin.template:
    src: 00-modulepath.sh.j2
    dest: /etc/profile.d/00-modulepath.sh
    owner: root
    group: root
    mode: '00644'
