- import_tasks: packages.yml
  tags: packages

- import_tasks: multipath.yml
  tags: multipath

- import_tasks: services.yml
  tags: services

- import_tasks: chrony.yml
  tags: chrony

- name: run role c2-node-exporter
  ansible.builtin.import_role:
    name: c2-node-exporter
  tags: c2-node-exporter
