- name: install /etc/multipath.conf
  ansible.builtin.copy:
    content: |
      defaults {
          user_friendly_names yes
      }
    dest: /etc/multipath.conf

- name: install /etc/multipath/bindings
  ansible.builtin.command:
    cmd: touch /etc/multipath/bindings
    creates: /etc/multipath/bindings
