- name: install package nfs-utils
  ansible.builtin.dnf:
    name: nfs-utils
    state: present
    update_cache: yes

- name: create mount point directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
  loop: "{{ nfs_mounts }}"

- name: add mounts to /etc/fstab
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    dump: "{{ item.dump }}"
    passno: "{{ item.passno }}"
    state: mounted
  loop: "{{ nfs_mounts }}"
