# rocky*.repo files contained in package rocky-repos
- name: install /etc/yum.repos.d/rocky*.repo
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/yum.repos.d/{{ item }}
  loop:
    - c2-local.repo
    - rocky-addons.repo
    - rocky-devel.repo
    - rocky-extras.repo
    - rocky.repo

- name: install packages
  ansible.builtin.dnf:
    name:
      ## packages to maintain parity with ubuntu
      - device-mapper-multipath
      # package polkit installed as dependency of udisks2
      - udisks2
      - upower
      ## misc packages
      - bind-utils
      # repo: epel
      #- netcat
      - nmap
      # repo: appstream
      - nmap-ncat
      - podman
      - tar
      - traceroute
      - which
    state: present
    update_cache: yes
