- name: set password for root and rocky users
  ansible.builtin.user:
    name: "{{ item }}"
    password: "{{ default_password | password_hash( hashtype='sha512', salt='shio' ) }}"
  loop: [ root , rocky ]
