# modified from rocky*.repo files in package rocky-repos
- name: install /etc/yum.repos.d/rocky*.repo
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/yum.repos.d/{{ item }}
  loop:
    - rocky-addons.repo
    - rocky-devel.repo
    - rocky-extras.repo
    - rocky.repo

- name: install /etc/yum.repos.d/c2-local.repo
  ansible.builtin.copy:
    content: |
      [c2-local]
      name=Carina 2.0 local RPM repository
      baseurl=http://{{ rpm_repo_ip }}:{{ rpm_repo_port }}/rpm/{{ distros[distro]['name'] }}
      gpgcheck=0
      enabled=0
    dest: /etc/yum.repos.d/c2-local.repo
    owner: root
    group: root
    mode: '0644'

# for packages falcon-sensor and wallet-client
- name: install /etc/yum.repos.d/stanford.repo
  ansible.builtin.copy:
    content: |
      # https://yum.stanford.edu/repos/stanford/stanford-EL9/stanford-EL9-x86_64.repo
      [stanford]
      name=Stanford RPMs for EL9 x86_64
      baseurl=https://yum.stanford.edu/repos/stanford/stanford-EL9/stanford-EL9-x86_64
      gpgcheck=1
      enabled=0
      countme=1
      gpgkey=https://yum.stanford.edu/STANFORD-GPG-KEY
    dest: /etc/yum.repos.d/stanford.repo
    owner: root
    group: root
    mode: '0644'

- name: install epel-release package
  ansible.builtin.dnf:
    name: epel-release
    state: present
    update_cache: yes

- name: disable epel repo
  community.general.dnf_config_manager:
    name: epel
    state: disabled

- name: disable epel-cisco-openh264 repo
  community.general.dnf_config_manager:
    name: epel-cisco-openh264
    state: disabled
  when: distros[distro]['el'] == 'el9'

- block:
    - name: import duo repo key
      ansible.builtin.rpm_key:
        key: https://duo.com/DUO-GPG-PUBLIC-KEY.asc
        state: present
    - name: install /etc/yum.repos.d/duosecurity.repo
      ansible.builtin.copy:
        content: |
          [duosecurity]
          name=Duo Security Repository
          baseurl=https://pkg.duosecurity.com/RedHat/$releasever/$basearch
          enabled=0
          gpgcheck=1
        dest: /etc/yum.repos.d/duosecurity.repo
        owner: root
        group: root
        mode: '0644'
  when: inventory_hostname in groups['c2_krb5_ldap_client']

# for ossec-hids-server package:
# https://www.ossec.net/download-ossec/#centos
# https://updates.atomicorp.com/channels/atomic/rocky/9/x86_64/RPMS/atomic-release-1.0-23.el9.art.noarch.rpm
- name: install /etc/yum.repos.d/atomic.repo
  ansible.builtin.copy:
    content: |
      [atomic]
      name = Rocky / Red Hat Enterprise Linux $releasever - atomic
      mirrorlist = https://updates.atomicorp.com/channels/mirrorlist/atomic/rocky-$releasever-$basearch
      enabled = 0
      protect = 0
      gpgkey = https://www.atomicorp.com/RPM-GPG-KEY.atomicorp.txt
      gpgcheck = 1
    dest: /etc/yum.repos.d/atomic.repo
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname in groups['c2_minsec_node']

- block:
    # https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo
    - name: install /etc/yum.repos.d/cuda-rhel9.repo
      ansible.builtin.copy:
        content: |
          [cuda-rhel9-x86_64]
          name=cuda-rhel9-x86_64
          baseurl=https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64
          enabled=0
          gpgcheck=1
          gpgkey=https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/D42D0685.pub
        dest: /etc/yum.repos.d/cuda-rhel9.repo
        owner: root
        group: root
        mode: '0644'
      when: distros[distro]['el'] == 'el9'
    # https://developer.download.nvidia.com/compute/cuda/repos/rhel10/x86_64/cuda-rhel10.repo
    - name: install /etc/yum.repos.d/cuda-rhel10.repo
      ansible.builtin.copy:
        content: |
          [cuda-rhel10-x86_64]
          name=cuda-rhel10-x86_64
          baseurl=https://developer.download.nvidia.com/compute/cuda/repos/rhel10/x86_64
          enabled=0
          gpgcheck=1
          gpgkey=https://developer.download.nvidia.com/compute/cuda/repos/rhel10/x86_64/CDF6BA43.pub
        dest: /etc/yum.repos.d/cuda-rhel10.repo
        owner: root
        group: root
        mode: '0644'
      when: distros[distro]['el'] == 'el10'
  when: inventory_hostname in groups['c2_gpu_node']

# https://raw.githubusercontent.com/TurboVNC/repo/main/TurboVNC.repo
- name: install /etc/yum.repos.d/turbovnc.repo
  ansible.builtin.copy:
    content: |
      [turbovnc]
      name=TurboVNC official RPMs
      baseurl=https://packagecloud.io/dcommander/turbovnc/rpm_any/rpm_any/$basearch
      repo_gpgcheck=1
      gpgcheck=1
      gpgkey=https://packagecloud.io/dcommander/turbovnc/gpgkey
             https://raw.githubusercontent.com/TurboVNC/repo/main/VGL-GPG-KEY
             https://raw.githubusercontent.com/TurboVNC/repo/main/VGL-GPG-KEY-1024
      enabled=0
      # exclude beta releases
      excludepkgs=turbovnc-*.*.9[0-9]-*
      sslverify=1
      sslcacert=/etc/pki/tls/certs/ca-bundle.crt
    dest: /etc/yum.repos.d/turbovnc.repo
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname in groups['c2_compute_node']

- block:
    - name: import grafana repo key
      ansible.builtin.rpm_key:
        key: https://rpm.grafana.com/gpg.key
        state: present
    - name: install /etc/yum.repos.d/grafana.repo
      ansible.builtin.copy:
        content: |
          [grafana]
          name=grafana
          baseurl=https://rpm.grafana.com
          repo_gpgcheck=0
          enabled=0
          gpgcheck=1
          gpgkey=https://rpm.grafana.com/gpg.key
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
        dest: /etc/yum.repos.d/grafana.repo
        owner: root
        group: root
        mode: '0644'
  when: inventory_hostname in groups['c2_grafana']
