- name: start/enable services
  ansible.builtin.systemd_service:
    name: "{{ item }}.service"
    state: started
    enabled: yes
    daemon_reload: yes
  loop:
    - acpid
    - polkit
    - sysstat
    - udisks2
    - upower

- name: stop/disable services
  ansible.builtin.systemd_service:
    name: "{{ item }}.service"
    state: stopped
    enabled: no
    daemon_reload: yes
  loop: []
