splunk_client_index: src_carina_unix
splunk_deployment_server_port: 8089
splunk_deployment_server: ciaspdmprd01.{{ domain }}
splunk_indexer_servers_port: 9996
splunk_indexer_servers:
  - ciaspidxprd01.{{ domain }}
  - ciaspidxprd02.{{ domain }}
  - ciaspidxprd03.{{ domain }}
  - ciaspidxprd04.{{ domain }}
  - ciaspidxprd05.{{ domain }}
  - ciaspidxprd06.{{ domain }}
splunk_client_admin_username: admin
splunk_client_admin_password: "{{ lookup('env', 'SPLUNK_CLIENT_ADMIN_PASSWORD') }}"
splunk_client_tls_key: "/var/tmp/c2-splunk-client-tls-crt/splunk.key"
splunk_client_tls_key_passphrase: "{{ lookup('env', 'SPLUNK_CLIENT_TLS_KEY_PASSPHRASE') }}"
splunk_client_tls_csr: "/var/tmp/c2-splunk-client-tls-crt/splunk.csr"
splunk_client_tls_crt: "/var/tmp/c2-splunk-client-tls-crt/splunk.crt"
splunk_rootca_tls_crt: "/var/tmp/c2-splunk-client-tls-crt/rootca.crt"
