prometheus_version: 3.6.0
prometheus_tgz_dir: prometheus-{{ prometheus_version }}.linux-amd64
prometheus_tgz: "{{ prometheus_tgz_dir }}.tar.gz"
prometheus_tgz_url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_tgz }}
prometheus_tgz_sha256: 2002ef4a55a64161affccd2786c7081d4e3b3a8d08786a98b3bb110971414916
prometheus_user: prometheus
prometheus_uid: 9100
prometheus_group: "{{ prometheus_user }}"
prometheus_gid: "{{ prometheus_uid }}"
prometheus_data_dir: /srv/prometheus/data
prometheus_log_dir: /srv/prometheus/log
prometheus_exec_file: /usr/local/sbin/prometheus
prometheus_config_file: /etc/prometheus/prometheus.yml
prometheus_retention_hours: 12
prometheus_scrape_interval_seconds: 15
