- name: create group {{ node_exporter_group }}
  ansible.builtin.group:
    name: "{{ node_exporter_group }}"
    gid: "{{ node_exporter_gid }}"

- name: create user {{ node_exporter_user }}
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    uid: "{{ node_exporter_uid }}"
    group: "{{ node_exporter_group }}"
    home: /nonexistent
    create_home: no
    shell: /usr/sbin/nologin

- name: fetch node_exporter tarball
  ansible.builtin.get_url:
    url: "{{ node_exporter_tgz_url }}"
    dest: /var/tmp/{{ node_exporter_tgz }}
    checksum: "sha256:{{ node_exporter_tgz_sha256 }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: '0644'

- name: extract node_exporter tarball
  ansible.builtin.unarchive:
    src: /var/tmp/{{ node_exporter_tgz }}
    dest: /var/tmp
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    remote_src: yes

- name: copy node_exporter binary to /usr/local/sbin
  ansible.builtin.copy:
    src: /var/tmp/{{ node_exporter_tgz_dir }}/node_exporter
    dest: /usr/local/sbin/node_exporter
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: '0750'
    remote_src: yes

- name: install /etc/systemd/system/node_exporter.service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  register: nesrv

- name: start/restart and enable node_exporter.service
  ansible.builtin.systemd_service:
    name: node_exporter.service
    state: "{{ 'restarted' if nesrv.changed else 'started' }}"
    enabled: yes
    daemon_reload: yes
