apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hub-cluster-pod
  annotations:
    configmanagement.gke.io/cluster-selector: jupyterhub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hub-cluster-pod
subjects:
- kind: ServiceAccount
  name: hub
  namespace: jupyter
