# ./users/arvindsk/kustomization.yaml
namespace: arvindsk

resources:
- ../../base/user
- ../../base/configmaps


patches:
- target:
    kind: Namespace
    name: default
  patch: |-
    - op: replace
      path: /metadata/name
      value: arvindsk
- target:
    kind: PersistentVolume
    name: cephfs-static-home
  patch: |-
    - op: replace
      path: /metadata/name
      value: cephfs-static-home-arvindsk
    - op: replace
      path: /spec/csi/volumeHandle
      value: cephfs-static-home-arvindsk
- target:
    kind: PersistentVolume
    name: cephfs-static-pi
  patch: |-
    - op: replace
      path: /metadata/name
      value: cephfs-static-pi-arvindsk
    - op: replace
      path: /spec/csi/volumeHandle
      value: cephfs-static-pi-arvindsk
- target:
    kind: PersistentVolumeClaim
    name: cephfs-static-home
  patch: |-
    - op: replace
      path: /spec/volumeName
      value: cephfs-static-home-arvindsk
- target:
    kind: PersistentVolumeClaim
    name: cephfs-static-pi
  patch: |-
    - op: replace
      path: /spec/volumeName
      value: cephfs-static-pi-arvindsk
- target:
    kind: Service
    name: jupyter
  patch: |-
    - op: replace
      path: /spec/selector/hub.jupyter.org~1username
      value: arvindsk
