- ansible.builtin.include_tasks:
    file: ghashr.yml
    apply:
      tags:
        - ghashr
  tags:
    - always

- name: run role c2-ansible
  ansible.builtin.include_role:
    name: c2-ansible
    apply:
      tags:
        - ansible
  tags:
    - always
