base_os_packages:
  ## maintain parity with ubuntu
  - acpid
  # package polkit installed as dependency of udisks2
  - udisks2
  - upower
  ## misc packages
  - bc
  - bind-utils
  - dnf-plugins-core
  - git
  - hwloc
  - iperf3
  - lsof
  - nmap
  - nmap-ncat
  - openldap-clients
  - pciutils
  - podman
  - podman-docker
  - python3-pip
  - rsync
  - sysstat
  - tar
  - tmux
  - traceroute
  - which

base_os_epel_packages:
  - htop

lmod_modulepath: /software/modulefiles

root_infra_ssh_private_key: "{{ lookup('env', 'ROOT_INFRA_SSH_PRIVATE_KEY') }}"
root_infra_ssh_public_key: "{{ lookup('env', 'ROOT_INFRA_SSH_PUBLIC_KEY') }}"
