slurm_rpm_builder_base_container_name: "{{ distro_container_name }}"
slurm_rpm_builder_base_container_tag: "{{ distro_container_tag }}"
# todo: rocky 10.0 doesn't have package http-parser-devel which
#       is a dependency for building slurmrestd package. for rocky 9.6
#       install the following additional packages:
#       http-parser-devel json-c-devel systemd
#slurm_rpm_builder_base_container_tag: 9.6
slurm_rpm_builder_base_container_image: "{{ slurm_rpm_builder_base_container_name }}:{{ slurm_rpm_builder_base_container_tag }}"
slurm_rpm_builder_container_packages: "@development dbus-devel hwloc libbpf-devel mariadb-devel munge-devel munge-libs pam-devel perl-devel perl-ExtUtils-MakeMaker readline-devel {{ 'http-parser-devel json-c-devel systemd' if slurm_rpm_builder_base_container_tag == '9.6' else '' }}"
slurm_rpm_builder_container_context_dir: /var/tmp/slurm-rpm-builder-container
slurm_rpm_builder_container_name: localhost/slurm-rpm-builder
slurm_rpm_builder_container_tag: "{{ slurm_version }}"
slurm_rpm_builder_container_image: "{{ slurm_rpm_builder_container_name }}:{{ slurm_rpm_builder_container_tag }}"
slurm_rpm: slurm-{{ slurm_version }}-1.el10.x86_64.rpm
