- name: install wallet-client package
  ansible.builtin.dnf:
    name: wallet-client-{{ wallet_client_version }}
    state: present
    update_cache: yes
    enablerepo: stanford

- name: install new user home quota script
  ansible.builtin.tempalate:
    src: new-user-home-quota.sh.j2
    dest: /admin/bin/set-home-quota/set-home-quota.sh
    owner: root
    group: "carina_admins"
    mode: "0750"

- name: run role c2-ansible
  ansible.builtin.include_role:
    name: c2-ansible
    apply:
      tags:
        - ansible
  tags:
    - always
