- ansible.builtin.include_tasks:
    file: admin-node.yml
    apply:
      tags:
        - admin-node
  tags:
    - always

- ansible.builtin.include_tasks:
    file: slurm-db-backup.yml
    apply:
      tags:
        - slurm-db-backup
  tags:
    - always
