# install cert and key if missing
- name: install prod API cert
  ansible.builtin.copy:
    content: "{{ lookup('pipe', 'wallet get file password/its-rc/carina-nero/carina-wg-api-prod-crt | base64') | b64decode }}"
    dest: /admin/bin/project_manager/c2-wgm-api-prod.pem
    owner: root
    group: carina_admins
    mode: '00600'

- name: install prod API key
  ansible.builtin.copy:
    content: "{{ lookup('pipe', 'wallet get file password/its-rc/carina-nero/carina-wg-api-prod-key | base64') | b64decode }}"
    dest: /admin/bin/project_manager/c2-wgm-api-prod.key
    owner: root
    group: carina_admins
    mode: '00600'

- name: install dev API cert
  ansible.builtin.copy:
    content: "{{ lookup('pipe', 'wallet get file password/its-rc/carina-nero/carina-wg-api-dev-crt | base64') | b64decode }}"
    dest: /admin/bin/project_manager/c2-wgm-api-dev.pem
    owner: root
    group: carina_admins
    mode: '00600'

- name: install dev API key
  ansible.builtin.copy:
    content: "{{ lookup('pipe', 'wallet get file password/its-rc/carina-nero/carina-wg-api-dev-key | base64') | b64decode }}"
    dest: /admin/bin/project_manager/c2-wgm-api-dev.key
    owner: root
    group: carina_admins
    mode: '00600'

# deploy script
- name: install project manager script
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: carina_admins
    mode: "0750"
  loop:
    - { src: 'files/admin/bin/project_manager/project_manager.py', dest: '/admin/bin/project_manager/project_manager.py'}
    - { src: 'files/admin/bin/project_manager/requirements.txt', dest: '/admin/bin/project_manager/requirements.txt'}
