apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: artifact-registry
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gsm-store               # name of the SecretStore (or kind specified)
  target:
    name: artifact-registry  # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson  # name of the GCPSM secret key
    remoteRef:
      key: artifact-registry-key
