apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-static-pi
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 498T
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: csi-cephfs-pi-client-secret
      namespace: cephfs
    volumeAttributes:
      clusterID: cc06bc72-cacd-11eb-8bdd-97416ba6ca5f
      fsName: hc-fs
      rootPath: /volumes/stanford/pi/8a38c8df-cfcd-4d8c-bee5-ad121dcc50b3
      staticVolume: "true"
    volumeHandle: cephfs-static-pi-default
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem