apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-static-home
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 305T
  volumeMode: Filesystem
  volumeName: cephfs-static-home-default