# ./base/user/kustomization.yaml
resources:
- namespace.yaml
#- cephfs-static-home-pvc.yaml
#- cephfs-static-home.yaml
- cephfs-static-pi-pvc.yaml
- cephfs-static-pi.yaml
- default-sidecar-policy.yaml
- jupyter-service.yaml
- munge-key.yaml
- new-start-notebook.yaml
- artifact-registry-secret.yaml
- slurm-node-conf-configmap.yaml
