# this is not used. /usr/local/bin/new-start-notebook.sh in the image is
# used instead. see the script in repository stanford-rc/nero-jupyter .
apiVersion: v1
kind: ConfigMap
metadata:
  name: new-start-notebook
data:
  new-start-notebook.sh: |
    #!/bin/bash
    # Copyright (c) Jupyter Development Team.
    # Distributed under the terms of the Modified BSD License.

    set -e

    export USER=$JUPYTERHUB_USER
    export HOME=/share/pi/home/$JUPYTERHUB_USER

    #make sure home is set correctly
    export HOME=/share/pi/home/$JUPYTERHUB_USER

    #cd $HOME
    cd /share/pi/home/$JUPYTERHUB_USER
    echo "start-notebook.sh running"

    if [[ ! -z "${JUPYTERHUB_API_TOKEN}" ]]; then
      # launched by JupyterHub, use single-user entrypoint
      export USER=$JUPYTERHUB_USER
      export HOME=/share/pi/home/$JUPYTERHUB_USER
      #env
      exec /bin/bash -c "export NB_USER=$JUPYTERHUB_USER; export HUB_PORT_8081_TCP_PROTO=$HUB_PORT_8081_TCP_PROTO;export HUB_SERVICE_HOST=$HUB_SERVICE_HOST;export HUB_PORT_8081_TCP_ADDR=$HUB_PORT_8081_TCP_ADDR;export HUB_SERVICE_PORT=$HUB_SERVICE_PORT;export JUPYTERHUB_CLIENT_ID=$JUPYTERHUB_CLIENT_ID; export JUPYTERHUB_BASE_URL=$JUPYTERHUB_BASE_URL;export JUPYTERHUB_USER=$JUPYTERHUB_USER;export JUPYTERHUB_SERVICE_PREFIX=$JUPYTERHUB_SERVICE_PREFIX;export JUPYTERHUB_API_URL=$JUPYTERHUB_API_URL;export JUPYTERHUB_HOST=$JUPYTERHUB_HOST;export JUPYTERHUB_OAUTH_CALLBACK_URL=$JUPYTERHUB_OAUTH_CALLBACK_URL;export JUPYTERHUB_API_TOKEN=$JUPYTERHUB_API_TOKEN;export JUPYTER_IMAGE_SPEC=$JUPYTER_IMAGE_SPEC;export JUPYTERHUB_CLIENT_ID=$JUPYTERHUB_CLIENT_ID;export JUPYTERHUB_ADMIN_ACCESS=$JUPYTERHUB_ADMIN_ACCESS;export JUPYTERHUB_SERVICE_PREFIX=$JUPYTERHUB_SERVICE_PREFIX;export JUPYTERHUB_API_URL=$JUPYTERHUB_API_URL;export JUPYTERHUB_HOST=$JUPYTERHUB_HOST;export JUPYTERHUB_OAUTH_CALLBACK_URL=$JUPYTERHUB_OAUTH_CALLBACK_URL;export JPY_API_TOKEN=$JPY_API_TOKEN;export JUPYTERHUB_API_TOKEN=$JUPYTERHUB_API_TOKEN;export PROXY_API_PORT=$PROXY_API_PORT; export PROXY_API_PORT_8001_TCP_PORT=$PROXY_API_PORT_8001_TCP_PORT; export JUPYTERHUB_ADMIN_ACCESS=$JUPYTERHUB_ADMIN_ACCESS; export HUB_PORT_8081_TCP_PROTO=$HUB_PORT_8081_TCP_PROTO; export HUB_SERVICE_HOST=$HUB_SERVICE_HOST;export JUPYTERHUB_CLIENT_ID=$JUPYTERHUB_CLIENT_ID;export JUPYTERHUB_SERVICE_PREFIX=$JUPYTERHUB_SERVICE_PREFIX; export HUB_PORT_8081_TCP_ADDR=$JUPYTERHUB_SERVICE_PREFIX; export HUB_SERVICE_PORT=$HUB_SERVICE_PORT; export JUPYTERHUB_API_URL=$JUPYTERHUB_API_URL; export JUPYTERHUB_HOST=$JUPYTERHUB_HOST; export JPY_API_TOKEN=$JPY_API_TOKEN; export JUPYTERHUB_OAUTH_CALLBACK_URL=$JUPYTERHUB_OAUTH_CALLBACK_URL;cd /share/pi/home/$JUPYTERHUB_USER;/usr/local/bin/start-singleuser.sh $*"

    #  exec /usr/local/bin/start-singleuser.sh $*
    else
        _CONDA_ROOT="/share/sw/open/anaconda/3"
        \. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
        _conda_activate
        jupyter lab $*
    fi
