- name: check for required secrets environment variables
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: check for required secrets environment variables
      fail:
        msg: required secret environment variable {{ item }} is not set!
      when: lookup('env', item) | default('', true) | length == 0
      loop:
        - ANSIBLE_SSH_PRIVATE_KEY_FILE
        - ANSIBLE_SSH_PUBLIC_KEY_FILE
        - DEFAULT_PASSWORD
        - GH_ACCESS_TOKEN
        - IDRAC_PASSWORD
        - IDRAC_USERNAME
        - MUNGE_KEY_B64
        - OOD_CERTBOT_DNS_GOOGLE_CREDENTIALS_JSON_B64
        - OOD_OIDC_CLIENT_ID
        - OOD_OIDC_CLIENT_SECRET
        - SLURM_DB_ROOT_PASSWORD
        - SLURM_DB_SLURM_PASSWORD
        - SPLUNK_CLIENT_ADMIN_PASSWORD
        - SPLUNK_CLIENT_TLS_KEY_PASSPHRASE
      run_once: yes
      tags:
        - always
