- import_playbook: c2-check-env.yml

- name: configure compute node
  hosts: c2_compute_node
  become: yes
  roles:
    - name: c2-base-os
      tags: c2-base-os
    - name: c2-compute-node
      tags: c2-compute-node
