- import_playbook: c2-check-env.yml

- name: check for kvm_guests extra variable
  hosts: localhost
  gather_facts: no
  tasks:
    - name: check for kvm_guests extra variable
      fail:
        msg: "{{ msg }}"
      vars:
        msg: extra variable kvm_guests is not defined, is null/empty, or is not a subset of host group c2_kvm_guest
      when: kvm_guests is not defined or kvm_guests is none or kvm_guests | length == 0 or kvm_guests is not subset(groups['c2_kvm_guest'])
    - name: show contents of kvm_guests extra variable
      debug:
        var: kvm_guests

- name: delete kvm guests and disk volumes
  hosts: "{{ kvm_guests }}"
  connection: ssh
  become: yes
  gather_facts: no
  tasks:

    - name: delete kvm guests
      delegate_to: "{{ kvm_host }}"
      block:

        - name: destroy kvm guests
          community.libvirt.virt:
            name: "{{ inventory_hostname }}"
            command: destroy
          ignore_errors: true

        - name: undefine kvm guests
          community.libvirt.virt:
            name: "{{ inventory_hostname }}"
            command: undefine
            # remove nvram and all other metadata
            force: yes
          ignore_errors: true

        - name: delete boot and data disk volumes
          community.libvirt.virt_volume:
            pool: "{{ hostvars[kvm_host]['pool'] }}"
            name: "{{ inventory_hostname }}-{{ item }}"
            state: absent
          loop:
            - boot
            - data
