- import_playbook: c2-check-env.yml

- name: converge /etc/fstab and remount nfs mounts on nfs clients
  hosts: c2_nfs_client
  become: yes
  tasks:

    - name: converge /etc/fstab
      ansible.posix.mount:
        src: "{{ item.src }}"
        path: "{{ item.path }}"
        fstype: "{{ item.fstype }}"
        opts: "{{ item.opts }}"
        dump: "{{ item.dump }}"
        passno: "{{ item.passno }}"
        state: present
      loop: "{{ nfs_mounts }}"
      register: fstab

    - name: remount nfs mounts
      ansible.posix.mount:
        path: "{{ item.path }}"
        state: remounted
      loop: "{{ nfs_mounts }}"
      when: fstab is changed

- import_playbook: c2-clean-env.yml
