- import_playbook: c2-check-env.yml

- name: get host power status
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: get host {{ inventory_hostname }} power status
      ansible.builtin.shell:
        cmd: |
          sshpass \
          -p "$IDRAC_PASSWORD" \
          ssh \
          -l "$IDRAC_USERNAME" \
          {{ idrac_ip }} \
          racadm getsysinfo -s | grep 'Power Status' | awk '{print $NF}'
      environment:
        IDRAC_PASSWORD: "{{ idrac_password }}"
        IDRAC_USERNAME: "{{ idrac_username }}"
      register: pwrstatus

    - debug:
        msg: "{{ pwrstatus.stdout }}"

- import_playbook: c2-clean-env.yml
