- import_playbook: c2-check-env.yml

- name: check for pxe_clients extra variable
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "{{ msg }}"
      fail:
        msg: "{{ msg }}"
      vars:
        msg: extra variable pxe_clients is not defined, is null/empty, or is not a subset of host group c2_pxe_client
      when: pxe_clients is not defined or pxe_clients is none or pxe_clients | length == 0 or pxe_clients is not subset(groups['c2_pxe_client'])
    - debug:
        var: pxe_clients

- name: configure dnsmasq and set pxe clients to net boot
  hosts: c2_pxe_server
  become: yes
  gather_facts: no
  tasks:
    - name: configure dnsmasq
      ansible.builtin.include_role:
        name: c2-dnsmasq
    - name: set pxe clients to net boot
      ansible.builtin.include_role:
        name: c2-pxe-config
      vars:
        pxe_clients: "{{ pxe_clients }}"
        pxe_mode: netinstall

- name: power cycle pxe clients for pxe boot auto-install
  hosts: "{{ pxe_clients }}"
  connection: local
  gather_facts: no
  tasks:

    - name: bare metal pxe clients
      ansible.builtin.include_tasks: c2-pxe-install-bare-metal-install.yml
      when: inventory_hostname not in groups['c2_kvm_guest']

    - name: kvm guest pxe clients
      ansible.builtin.include_tasks: c2-pxe-install-kvm-guest-install.yml
      when: inventory_hostname in groups['c2_kvm_guest']

- name: configure pxe clients to local boot
  hosts: c2_pxe_server
  become: yes
  gather_facts: no
  tasks:
    - name: configure pxe clients to local boot
      ansible.builtin.include_role:
        name: c2-pxe-config
      vars:
        pxe_clients: "{{ pxe_clients }}"

- name: power on pxe clients and wait for ssh
  hosts: "{{ pxe_clients }}"
  connection: local
  gather_facts: no
  tasks:

    - name: bare metal pxe clients
      ansible.builtin.include_tasks: c2-pxe-install-bare-metal-ping.yml
      when: inventory_hostname not in groups['c2_kvm_guest']

    - name: kvm guest pxe clients
      ansible.builtin.include_tasks: c2-pxe-install-kvm-guest-ping.yml
      when: inventory_hostname in groups['c2_kvm_guest']

- name: ping pxe clients {{ pxe_clients }}
  hosts: "{{ pxe_clients }}"
  gather_facts: no
  tasks:
    - name: ping pxe clients
      ansible.builtin.ping:

- import_playbook: c2-clean-env.yml
