- name: power off pxe clients
  delegate_to: "{{ hostvars[inventory_hostname]['kvm_host'] }}"
  connection: ssh
  become: yes
  block:

    - name: destroy kvm guests
      community.libvirt.virt:
        name: "{{ inventory_hostname }}"
        command: destroy
      ignore_errors: true

    - name: undefine kvm guests
      community.libvirt.virt:
        name: "{{ inventory_hostname }}"
        command: undefine
      ignore_errors: true

    - name: delete boot and data disk volumes
      community.libvirt.virt_volume:
        pool: "{{ hostvars[kvm_host]['pool'] }}"
        name: "{{ inventory_hostname }}-{{ item }}"
        state: absent
      loop:
        - boot
        - data

    - name: create boot and data disk volumes
      community.libvirt.virt_volume:
        pool: "{{ hostvars[kvm_host]['pool'] }}"
        # name not required here since it's defined in volume xml
        #name: "{{ inventory_hostname }}-{{ item }}"
        state: present
        xml: "{{ lookup('template', 'volume.xml.j2') }}"
      loop:
        - boot
        - data

    - name: define kvm guests for pxe boot
      community.libvirt.virt:
        # name not required here since it's defined in domain xml
        #name: "{{ inventory_hostname }}"
        command: define
        xml: "{{ lookup('template', 'domain.xml.j2') }}"
      vars:
        pxe_mode: netinstall

    - name: start kvm guests
      community.libvirt.virt:
        name: "{{ inventory_hostname }}"
        state: running

    - name: wait for pxe provisioning of kvm guests to finish
      community.libvirt.virt:
        name: "{{ inventory_hostname }}"
        command: info
      register: info
      until: info[inventory_hostname]['state'] == 'shutdown'
      # retry for 15 minutes
      retries: 30
      delay: 30

    - name: redefine kvm guests for local boot
      community.libvirt.virt:
        # name not required here since it's defined in domain xml
        #name: "{{ inventory_hostname }}"
        command: define
        xml: "{{ lookup('template', 'domain.xml.j2') }}"
