- import_playbook: c2-check-env.yml

- name: power cycle host
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: power cycle host {{ inventory_hostname }}
      ansible.builtin.shell:
        cmd: |
          sshpass \
          -p "$IDRAC_PASSWORD" \
          ssh \
          -l "$IDRAC_USERNAME" \
          {{ idrac_ip }} \
          racadm serveraction powercycle
      environment:
        IDRAC_PASSWORD: "{{ idrac_password }}"
        IDRAC_USERNAME: "{{ idrac_username }}"
      register: pwrcycle

    - debug:
        msg: "{{ pwrcycle.stdout }}"

- import_playbook: c2-clean-env.yml
