- import_playbook: c2-check-env.yml

- name: power up host
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: power up host {{ inventory_hostname }}
      ansible.builtin.shell:
        cmd: |
          sshpass \
          -p "$IDRAC_PASSWORD" \
          ssh \
          -l "$IDRAC_USERNAME" \
          {{ idrac_ip }} \
          racadm serveraction powerup
      environment:
        IDRAC_PASSWORD: "{{ idrac_password }}"
        IDRAC_USERNAME: "{{ idrac_username }}"
      register: pwrup

    - debug:
        msg: "{{ pwrup.stdout }}"
