- import_playbook: c2-check-env.yml

- name: configure pxe clients
  hosts: c2_pxe_server
  become: yes
  gather_facts: no
  tasks:
    - name: run role c2-pxe-config
      ansible.builtin.include_role:
        name: c2-pxe-config
