- name: update packages and reboot system
  hosts: all
  become: yes
  tasks:
    - name: update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes
      register: dnfresult
    - name: reboot system
      ansible.builtin.reboot:
      when: dnfresult is changed
