- hosts: k8s
  become: yes
  gather_facts: no
  tasks:
    - ansible.builtin.shell:
        cmd: |
          if [ -d /mnt/slurm-temp ]
          then
            rm -rf /mnt/slurm-temp/*
          fi
          for CID in $(crictl ps -a -q -s Exited)
          do
            crictl rm $CID
          done
          crictl rmi --prune
