- name: install certbot package
  ansible.builtin.dnf:
    name: certbot
    state: present
    update_cache: yes
    enablerepo: epel

- name: create venv {{ certbot_plugin_venv }}
  ansible.builtin.shell:
    cmd: |
      {{ ansible_python_interpreter }} -m venv {{ certbot_plugin_venv }}
    creates: "{{ certbot_plugin_venv }}"

# todo: document the upgrade behavioral variable
- name: install python package {{ certbot_dns_google_plugin_package }}
  ansible.builtin.pip:
    name: "{{ certbot_dns_google_plugin_package }}"
    executable: "{{ certbot_plugin_venv }}/bin/pip3"
    extra_args: "{{ '--upgrade' if upgrade is defined and upgrade else '' }}"

- name: link httpd tls key to live certbot key
  ansible.builtin.file:
    src: "{{ certbot_tls_key }}"
    dest: "{{ apache_tls_key }}"
    state: link
    force: yes

- name: link httpd tls cert to live certbot cert
  ansible.builtin.file:
    src: "{{ certbot_tls_crt }}"
    dest: "{{ apache_tls_crt }}"
    state: link
    force: yes

# todo: install service account json credentials file here
- name: install certbot dns google credentials json file {{ certbot_dns_google_credentials_file }}
  ansible.builtin.copy:
    content: "{{ certbot_dns_google_credentials_json }}"
    dest: "{{ certbot_dns_google_credentials_file }}"
    mode: '00600'

- name: get letsencrypt cert via certbot
  ansible.builtin.shell:
    cmd: |
      certbot certonly \
      --agree-tos \
      --deploy-hook 'systemctl restart httpd.service' \
      --dns-google \
      --dns-google-credentials {{ certbot_dns_google_credentials_file }} \
      --dns-google-project {{ certbot_dns_google_project }} \
      --dns-google-propagation-seconds {{ certbot_dns_google_propagation_seconds }} \
      --domain {{ ood_domain }} \
      --email {{ certbot_email }} \
      --no-eff-email \
      --non-interactive \
      --preferred-challenges dns-01 \
      {% if ood_certbot_staging is defined and ood_certbot_staging %}
      --reinstall \
      --staging
      {% else %}
      --reinstall
      {% endif %}
  environment:
    PATH: "{{ certbot_plugin_venv }}/bin:/bin:/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin"
  tags:
    - cbgetcrt
