- ansible.builtin.include_tasks:
    file: ood.yml
    apply:
      tags:
        - ood
  tags:
    - always

- ansible.builtin.include_tasks:
    file: certbot.yml
    apply:
      tags:
        - certbot
  tags:
    - always

- ansible.builtin.include_tasks:
    file: jupyterlab.yml
    apply:
      tags:
        - jupyterlab
  tags:
    - always

- ansible.builtin.include_tasks:
    file: rstudio-server.yml
    apply:
      tags:
        - rstudio-server
  tags:
    - always

- ansible.builtin.include_tasks:
    file: code-server.yml
    apply:
      tags:
        - code-server
  tags:
    - always

- ansible.builtin.include_tasks:
    file: matlab.yml
    apply:
      tags:
        - matlab
  tags:
    - always
