- ansible.builtin.include_tasks:
    file: ood.yml
    apply:
      tags:
        - ood
  tags:
    - always

- ansible.builtin.include_tasks:
    file: certbot.yml
    apply:
      tags:
        - certbot
  tags:
    - always

- ansible.builtin.include_tasks:
    file: jupyterlab.yml
    apply:
      tags:
        - jupyterlab
  tags:
    - always
