# https://osc.github.io/ood-documentation/latest/installation/install-software.html

- name: install required modularity modules
  ansible.builtin.dnf:
    name: '@{{ item }}'
    state: present
    update_cache: yes
    enablerepo: epel
  loop: "{{ modules }}"
  vars:
    modules:
      - ruby:3.3 # repo: epel
      - nodejs:20 # repo: epel

# todo: get url to gpg key and install it here

- name: install ood repo rpm package
  ansible.builtin.dnf:
    name: https://yum.osc.edu/ondemand/{{ ood_version }}/{{ ood_rpm }}
    state: present
    update_cache: yes
    disable_gpg_check: yes

- name: install packages
  ansible.builtin.dnf:
    name:
      - mod_auth_openidc
      - ondemand
    state: present
    update_cache: yes
    enablerepo: epel

- name: start/enable httpd.service
  ansible.builtin.systemd_service:
    name: httpd.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: generate self-signed tls certificate
  ansible.builtin.shell:
    cmd: |
      openssl req \
      -x509 \
      -newkey rsa:2048 \
      -keyout {{ apache_tls_key }} \
      -out {{ apache_tls_crt }} \
      -nodes \
      -days 1024 \
      -subj '/CN={{ public_name }}'
    creates: "{{ apache_tls_crt }}"

- name: configure mpm_event module
  ansible.builtin.template:
    src: etc/httpd/conf.d/mpm_event.conf.j2
    dest: /etc/httpd/conf.d/mpm_event.conf
    owner: root
    group: root
    mode: '00644'
  notify: restart httpd

# nb: don't redirect /.well-known/ from http to https to allow certbot
#     http validation. we use dns validation but can switch to http if
#     needed.
- name: install /opt/ood/ood-portal-generator/templates/ood-portal.conf.erb
  ansible.builtin.template:
    src: opt/ood/ood-portal-generator/templates/ood-portal.conf.erb.j2
    dest: /opt/ood/ood-portal-generator/templates/ood-portal.conf.erb
    owner: root
    group: root
    mode: '00644'
  notify: restart httpd

- name: install /etc/ood/config/nginx_stage.yml
  ansible.builtin.template:
    src: etc/ood/config/nginx_stage.yml.j2
    dest: /etc/ood/config/nginx_stage.yml
    owner: root
    group: root
    mode: '00644'
  notify: restart httpd

- name: install /etc/ood/config/ood_portal.yml
  ansible.builtin.template:
    src: etc/ood/config/ood_portal.yml.j2
    dest: /etc/ood/config/ood_portal.yml
    owner: root
    group: root
    mode: '00600'
  notify: restart httpd

- name: create directory /etc/ood/config/clusters.d
  ansible.builtin.file:
    path: /etc/ood/config/clusters.d
    state: directory

- name: install /etc/ood/config/clusters.d/{{ slurm_cluster_name }}.yml
  ansible.builtin.template:
    src: etc/ood/config/clusters.d/{{ slurm_cluster_name }}.yml.j2
    dest: /etc/ood/config/clusters.d/{{ slurm_cluster_name }}.yml
    owner: root
    group: root
    mode: '00644'
  notify: restart httpd

- name: create directory /etc/ood/config/ondemand.d
  ansible.builtin.file:
    path: /etc/ood/config/ondemand.d
    state: directory

- name: install /etc/ood/config/ondemand.d/stanford.yml
  ansible.builtin.template:
    src: etc/ood/config/ondemand.d/stanford.yml.j2
    dest: /etc/ood/config/ondemand.d/stanford.yml
    owner: root
    group: root
    mode: '00644'
  notify: restart httpd

# https://osc.github.io/ood-documentation/latest/customizations.html#pinning-applications-to-the-dashboard
- name: install /etc/ood/config/ondemand.d/ondemand.yml
  ansible.builtin.copy:
    content: |
      pinned_apps:
        - 'sys/*'
    dest: /etc/ood/config/ondemand.d/ondemand.yml
    owner: root
    group: root
    mode: '00644'
  notify: restart httpd

- name: create directory /etc/ood/config/apps/dashboard/initializers
  ansible.builtin.file:
    path: /etc/ood/config/apps/dashboard/initializers
    state: directory

- name: install /etc/ood/config/apps/dashboard/initializers/ood.rb
  ansible.builtin.template:
    src: etc/ood/config/apps/dashboard/initializers/ood.rb.j2
    dest: /etc/ood/config/apps/dashboard/initializers/ood.rb
    owner: root
    group: root
    mode: '00644'
  notify: restart httpd

- name: install /etc/ood/config/apps/dashboard/env
  ansible.builtin.template:
    src: etc/ood/config/apps/dashboard/env.j2
    dest: /etc/ood/config/apps/dashboard/env
    owner: root
    group: root
    mode: '00644'
  notify: restart httpd

- name: create directory /etc/ood/config/apps/shell
  ansible.builtin.file:
    path: /etc/ood/config/apps/shell
    state: directory

- name: install /etc/ood/config/apps/shell/env
  ansible.builtin.template:
    src: etc/ood/config/apps/shell/env.j2
    dest: /etc/ood/config/apps/shell/env
    owner: root
    group: root
    mode: '00644'
  notify: restart httpd

- name: create directory /etc/ood/config/apps/bc_desktop/submit
  ansible.builtin.file:
    path: /etc/ood/config/apps/bc_desktop/submit
    state: directory

- name: install /etc/ood/config/apps/bc_desktop/{{ slurm_cluster_name }}.yml
  ansible.builtin.template:
    src: etc/ood/config/apps/bc_desktop/{{ slurm_cluster_name }}.yml.j2
    dest: /etc/ood/config/apps/bc_desktop/{{ slurm_cluster_name }}.yml
    owner: root
    group: root
    mode: '00644'
  notify: restart httpd

- name: install /etc/ood/config/apps/bc_desktop/submit/{{ slurm_cluster_name }}.yml.erb
  ansible.builtin.template:
    src: etc/ood/config/apps/bc_desktop/submit/{{ slurm_cluster_name }}.yml.erb.j2
    dest: /etc/ood/config/apps/bc_desktop/submit/{{ slurm_cluster_name }}.yml.erb
    owner: root
    group: root
    mode: '00644'
  notify: restart httpd

- name: install /var/www/ood/apps/sys/bc_desktop/template/script.sh.erb
  ansible.builtin.template:
    src: var/www/ood/apps/sys/bc_desktop/template/script.sh.erb.j2
    dest: /var/www/ood/apps/sys/bc_desktop/template/script.sh.erb
    owner: root
    group: root
    mode: '00755'
  notify: restart httpd

- name: create directory /var/www/ood/apps/dev/<user>
  ansible.builtin.file:
    path: /var/www/ood/apps/dev/{{ item }}
    state: directory
  loop: "{{ ood_dev_users }}"

- name: symlink /var/www/ood/apps/dev/<user>/gateway to /home/users/<user>/ondemand/dev
  ansible.builtin.file:
    src: /home/users/{{ item }}/ondemand/dev
    dest: /var/www/ood/apps/dev/{{ item }}/gateway
    state: link
    force: yes
  loop: "{{ ood_dev_users }}"

- name: create directory /var/www/ood/public
  ansible.builtin.file:
    path: /var/www/ood/public
    state: directory

- name: install /var/www/ood/public/logo.png
  ansible.builtin.copy:
    src: var/www/ood/public/logo.png
    dest: /var/www/ood/public/logo.png
    owner: root
    group: root
    mode: '00644'
  notify: restart httpd
