# https://osc.github.io/ood-documentation/latest/installation/install-software.html

- name: install required modularity modules
  ansible.builtin.dnf:
    name: '@{{ item }}'
    state: present
    update_cache: yes
    enablerepo: epel
  loop: "{{ modules }}"
  vars:
    modules:
      - ruby:3.3 # repo: epel
      - nodejs:20 # repo: epel

- name: install ood repo rpm package
  ansible.builtin.dnf:
    name: https://yum.osc.edu/ondemand/{{ ood_version }}/{{ ood_rpm }}
    state: present
    update_cache: yes
    disable_gpg_check: yes

- name: install packages
  ansible.builtin.dnf:
    name:
      - mod_auth_openidc
      - ondemand
    state: present
    update_cache: yes
    enablerepo: epel

- name: start/enable httpd.service
  ansible.builtin.systemd_service:
    name: httpd.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: generate self-signed tls certificate
  ansible.builtin.shell:
    cmd: |
      openssl req \
      -x509 \
      -newkey rsa:2048 \
      -keyout {{ apache_tls_key }} \
      -out {{ apache_tls_crt }} \
      -nodes \
      -days 1024 \
      -subj '/CN={{ ood_domain }}'
    creates: "{{ apache_tls_crt }}"

- name: create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop: "{{ ood_dirs }}"

- name: install files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /{{ item }}
    owner: root
    group: root
    mode: '00644'
  loop: "{{ ood_files }}"
  notify: restart httpd

- name: install templates
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /{{ item }}
    owner: root
    group: root
    mode: '00644'
  loop: "{{ ood_templates }}"
  notify: restart httpd

- name: create directories /var/www/ood/apps/dev/<user>
  ansible.builtin.file:
    path: /var/www/ood/apps/dev/{{ item }}
    state: directory
  loop: "{{ ood_dev_users }}"

- name: symlink /var/www/ood/apps/dev/<user>/gateway to /home/users/<user>/ondemand/dev
  ansible.builtin.file:
    src: /home/users/{{ item }}/ondemand/dev
    dest: /var/www/ood/apps/dev/{{ item }}/gateway
    state: link
    force: yes
  loop: "{{ ood_dev_users }}"

- name: symlink /var/www/ood/public/maintenance/assets to /var/www/ood/public/assets
  ansible.builtin.file:
    src: /var/www/ood/public/assets
    dest: /var/www/ood/public/maintenance/assets
    state: link
