- name: create directories /var/www/ood/apps/sys/rstudio-server/template/{bin,etc}
  ansible.builtin.file:
    path: /var/www/ood/apps/sys/rstudio-server/template/{{ item }}
    state: directory
    owner: root
    group: root
    mode: '00755'
  loop:
    - bin
    - etc

- name: install app files in /var/www/ood/apps/sys/rstudio-server
  ansible.builtin.template:
    src: var/www/ood/apps/sys/rstudio-server/{{ item.name }}.j2
    dest: /var/www/ood/apps/sys/rstudio-server/{{ item.name }}
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - name: form.yml.erb
      mode: '00644'
    - name: manifest.yml
      mode: '00644'
    - name: submit.yml.erb
      mode: '00644'
    - name: template/after.sh.erb
      mode: '00755'
    - name: template/before.sh.erb
      mode: '00755'
    - name: template/bin/auth
      mode: '00755'
    - name: template/script.sh.erb
      mode: '00755'
    - name: view.html.erb
      mode: '00644'

- name: install binary app files in /var/www/ood/apps/sys/rstudio-server
  ansible.builtin.copy:
    src: var/www/ood/apps/sys/rstudio-server/{{ item.name }}
    dest: /var/www/ood/apps/sys/rstudio-server/{{ item.name }}
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - name: icon.png
      mode: '00644'
