apiVersion: v1
data:
  tls-config.yaml: |-
    tls_server_config:
      cert_file: /certs/node-exporter/tls.crt
      key_file: /certs/node-exporter/tls.key
      client_auth_type: RequireAndVerifyClientCert
      client_ca_file: /certs/metrics-consumers/ca.crt
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"tls-config.yaml":"tls_server_config:\n  cert_file: /certs/node-exporter/tls.crt\n  key_file: /certs/node-exporter/tls.key\n  client_auth_type: RequireAndVerifyClientCert\n  client_ca_file: /certs/metrics-consumers/ca.crt"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"addons.gke.io/stackdriver":"stackdriver","k8s-app":"node-exporter","managed-by":"stackdriver","version":"latest"},"name":"node-exporter-tls-config","namespace":"kube-system","ownerReferences":[{"apiVersion":"addons.gke.io/v1alpha1","blockOwnerDeletion":true,"controller":true,"kind":"stackdriver","name":"stackdriver","uid":"acf82f4a-6a92-4ecc-92a3-50056c006398"}]}}
  creationTimestamp: "2022-05-15T01:09:05Z"
  labels:
    addons.gke.io/stackdriver: stackdriver
    k8s-app: node-exporter
    managed-by: stackdriver
    version: latest
  name: node-exporter-tls-config
  namespace: kube-system
  ownerReferences:
  - apiVersion: addons.gke.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: stackdriver
    name: stackdriver
    uid: acf82f4a-6a92-4ecc-92a3-50056c006398
  resourceVersion: "1546081116"
  uid: cf9f150d-4096-4fcd-bc3b-19cf46d3b1a5
