- name: stop and disable ondemand service
  ansible.builtin.systemd_service:
    name: ondemand.service
    state: stopped
    enabled: no
    daemon_reload: yes

- name: install package cpufrequtils
  ansible.builtin.apt:
    name: cpufrequtils
    state: present
    update_cache: yes

- name: install /etc/default/cpufrequtils
  ansible.builtin.copy:
    content: |
      GOVERNOR="performance"
    dest: /etc/default/cpufrequtils

- name: detect current governor
  ansible.builtin.shell:
    cmd: '[ "$( cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor | sort -u )" = "performance" ]'
  register: governor_result
  changed_when: false
  failed_when: false

# echo "performance" | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
- name: restart cpufrequtils service
  ansible.builtin.systemd_service:
    name: cpufrequtils.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: governor_result.rc != 0
