- name: stop and disable ondemand service
  ansible.builtin.systemd_service:
    name: ondemand.service
    state: stopped
    enabled: no
    daemon_reload: yes

- name: install package cpufrequtils
  ansible.builtin.apt:
    name: cpufrequtils
    state: present
    update_cache: yes

- name: install /etc/default/cpufrequtils
  ansible.builtin.copy:
    content: |
      GOVERNOR="performance"
    dest: /etc/default/cpufrequtils

- name: detect current governor
  ansible.builtin.command:
    cmd: cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
  register: governor_result
  changed_when: false

- name: set governor to performance on all cpus
  ansible.builtin.shell:
    cmd: echo "performance" | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
  when: governor_result.stdout != 'performance'
