- name: install packages
  ansible.builtin.dnf:
    name:
      - createrepo_c
    state: present
    update_cache: yes

- ansible.builtin.include_tasks:
    file: slurm.yml
    apply:
      tags:
        - slurm
  tags:
    - always

- ansible.builtin.include_tasks:
    file: rstudio-server.yml
    apply:
      tags:
        - rstudio-server
  tags:
    - always

- ansible.builtin.include_tasks:
    file: code-server.yml
    apply:
      tags:
        - code-server
  tags:
    - always
