- name: create slurm rpm build context directories for each distro
  ansible.builtin.file:
    path: "{{ path }}"
    state: directory
  loop: "{{ distros | dict2items }}"
  loop_control:
    loop_var: _distro
  vars:
    path: /var/tmp/slurm-rpm-builder-container-{{ _distro.value.name }}/tmp

- name: install containerfiles
  ansible.builtin.template:
    src: Containerfile.j2
    dest: /var/tmp/slurm-rpm-builder-container-{{ _distro.value.name }}/Containerfile
  loop: "{{ distros | dict2items }}"
  loop_control:
    loop_var: _distro

- name: install entrypoint scripts
  ansible.builtin.template:
    src: entrypoint.j2
    dest: /var/tmp/slurm-rpm-builder-container-{{ _distro.value.name }}/entrypoint
    mode: '00755'
  loop: "{{ distros | dict2items }}"
  loop_control:
    loop_var: _distro

- name: build container images
  containers.podman.podman_image:
    name: localhost/slurm-rpm-builder-{{ _distro.value.name }}
    tag: "{{ slurm_version }}"
    path: /var/tmp/slurm-rpm-builder-container-{{ _distro.value.name }}
    build:
      cache: no
      force_rm: yes
      format: oci
  loop: "{{ distros | dict2items }}"
  loop_control:
    loop_var: _distro

- name: prune images
  containers.podman.podman_prune:
    system: true

- name: build and install slurm rpms for each distro
  ansible.builtin.include_tasks:
    file: slurm-build.yml
  loop: "{{ distros | dict2items }}"
  loop_control:
    loop_var: _distro
