- name: stat slurm rpm to determine if rpms should be rebuilt
  ansible.builtin.stat:
    path: /srv/rpm/{{ _distro.value.name }}/slurm-{{ slurm_version }}-1.{{ _distro.value.el }}.x86_64.rpm
  register: statslurmrpm

- block:

    - name: build slurm rpms
      containers.podman.podman_container:
        name: slurm-rpm-builder-{{ _distro.value.name }}
        image: localhost/slurm-rpm-builder-{{ _distro.value.name }}:{{ slurm_version }}
        state: started
        detach: no
        volumes:
          - /var/tmp/slurm-rpm-builder-container-{{ _distro.value.name }}/tmp:/pwd
        rm: yes

    - name: sync to flush slurm rpms to disk
      ansible.builtin.command: sync
      changed_when: false

    - name: install slurm rpms
      ansible.builtin.shell:
        cmd: |
          set -e
          mkdir -p /srv/rpm/{{ _distro.value.name }}
          rm -fv /srv/rpm/{{ _distro.value.name }}/slurm-*.rpm
          mv -fv /var/tmp/slurm-rpm-builder-container-{{ _distro.value.name }}/tmp/slurm-*.rpm /srv/rpm/{{ _distro.value.name }}

  when: not statslurmrpm.stat.exists
  notify: update repo metadata
