- name: get splunkforwarder rpms for each distro
  ansible.builtin.get_url:
    url: "{{ splunk_forwarder_rpms[_distro.value.el]['url'] }}"
    dest: /srv/rpm/{{ _distro.value.name }}/{{ splunk_forwarder_rpms[_distro.value.el]['url'] | basename }}
    checksum: "sha256:{{ splunk_forwarder_rpms[_distro.value.el]['sha256'] }}"
    owner: root
    group: root
    mode: '00644'
  loop: "{{ distros | dict2items }}"
  loop_control:
    loop_var: _distro
  notify: update repo metadata
