- name: set net.ipv4.ip_forward=1
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: start/enable firwalld service
  ansible.builtin.systemd_service:
    name: firewalld.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: allow ports for services
  ansible.posix.firewalld:
    port: "{{ item }}"
    state: enabled
    immediate: true
    permanent: true
  loop:
    - 22/tcp   # ssh
    - 53/tcp   # dns
    - 53/udp   # dns
    - 67/udp   # dhcp/pxe
    - 69/udp   # tftp/pxe
    - 8000/tcp # c2-local repo
    - 9100/tcp # node_exporter

- name: enable nat for management and cluster networks
  ansible.posix.firewalld:
    rich_rule: rule family=ipv4 source address={{ item }} masquerade
    state: enabled
    immediate: true
    permanent: true
  loop:
    - "{{ network_mgmt_cidr }}"
    - "{{ network_cluster_cidr }}"
