- name: install packages
  ansible.builtin.dnf:
    name:
      - dnsmasq
      - grub2-efi-x64
      - nginx
      - shim-x64
      - syslinux
      - tftp
    state: present
    update_cache: yes

- name: install /etc/NetworkManager/NetworkManager.conf
  ansible.builtin.template:
    src: NetworkManager.conf.j2
    dest: /etc/NetworkManager/NetworkManager.conf
    owner: root
    group: root
    mode: '0644'
  register: nmconf

- name: restart NetworkManager
  ansible.builtin.systemd_service:
    name: NetworkManager.service
    state: restarted
    daemon_reload: yes
  when: nmconf is changed

# todo: verify this is still needed
#- name: add hostname to /etc/hosts
#  ansible.builtin.lineinfile:
#    path: /etc/hosts
#    regexp: '^127.0.0.1 localhost.*$'
#    line: '127.0.0.1 localhost {{ inventory_hostname }}'
#    owner: root
#    group: root
#    mode: '0644'

- name: install /etc/resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'

- name: install /etc/dnsmasq.conf
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
  register: dnsmasqconf

- name: restart dnsmasq
  ansible.builtin.systemd_service:
    name: dnsmasq.service
    state: restarted
    daemon_reload: yes
  when: dnsmasqconf is changed

- name: install /srv/pxelinux.0
  ansible.builtin.copy:
    src: "{{ pxelinux_base_dir }}/pxelinux.0"
    dest: /srv/pxelinux.0
    remote_src: yes
    owner: root
    group: root
    mode: '0644'

- name: install /srv/{ldlinux,libcom32,libutil,vesamenu}.c32
  ansible.builtin.copy:
    src: "{{ syslinux_base_dir }}/{{ item }}.c32"
    dest: /srv/{{ item }}.c32
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
  loop:
    - ldlinux
    - libcom32
    - libutil
    - vesamenu

- name: install /srv/{grubx64,shim}.efi
  ansible.builtin.copy:
    src: "{{ grubefi_base_dir }}/{{ item }}.efi"
    dest: /srv/{{ item }}.efi
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
  loop:
    - grubx64
    - shim

- name: create {{ distro }} iso image mount point directory
  file:
    path: /srv/{{ distro }}
    state: directory
    owner: root
    group: root

- name: install {{ distro }} iso image
  ansible.builtin.get_url:
    url: "{{ iso_url }}"
    dest: /srv/{{ distro }}.iso
    checksum: "sha256:{{ iso_sha256 }}"
    owner: root
    group: root
    mode: '0644'
  register: isoimg

- name: unmount {{ distro }} iso image
  ansible.posix.mount:
    src: /srv/{{ distro }}.iso
    path: /srv/{{ distro }}
    fstype: iso9660
    opts: auto,loop,ro
    state: absent
  when: isoimg is changed

- name: mount {{ distro }} iso image
  ansible.posix.mount:
    src: /srv/{{ distro }}.iso
    path: /srv/{{ distro }}
    fstype: iso9660
    opts: auto,loop,ro
    state: mounted

- name: run role c2-pxe-config
  ansible.builtin.include_role:
    name: c2-pxe-config

- name: install /etc/nginx/nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  register: nginxconf

- name: restart nginx
  ansible.builtin.systemd_service:
    name: nginx.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: nginxconf is changed

- name: sync to disk
  command: sync
  changed_when: false
