- name: install falcon-sensor package
  ansible.builtin.dnf:
    name: falcon-sensor-{{ falcon_sensor_version }}
    state: present
    update_cache: yes
    enablerepo: stanford

- name: get current cid
  ansible.builtin.command:
    cmd: /opt/CrowdStrike/falconctl -g --cid
  register: falconctl_cid_result
  failed_when: no
  changed_when: no

- name: get current tags
  ansible.builtin.command:
    cmd: /opt/CrowdStrike/falconctl -g --tags
  register: falconctl_tags_result
  changed_when: no

- name: set cid
  ansible.builtin.command:
    cmd: /opt/CrowdStrike/falconctl -s --cid=$FALCON_SENSOR_CID
  environment:
    FALCON_SENSOR_CID: "{{ falcon_sensor_cid }}"
  when: '"CID is not set." in falconctl_cid_result.stderr'
  register: falconctl_set_cid_result

- name: set tags
  ansible.builtin.command:
    cmd: /opt/CrowdStrike/falconctl -s --tags={{ falcon_sensor_tags }}
  when: '"Sensor grouping tags are not set." in falconctl_tags_result.stdout'
  register: falconctl_set_tags_result

- name: enable and start/restart falcon-sensor.service
  ansible.builtin.systemd_service:
    name: falcon-sensor.service
    enabled: yes
    state: "{{ 'restarted' if falconctl_set_cid_result.changed or falconctl_set_tags_result.changed else 'started' }}"
    daemon_reload: yes
