apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: carina-login-keytab
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gsm-store             # name of the SecretStore (or kind specified)
  target:
    name: carina-login-keytab      # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: krb5.keytab     # name of the GCPSM secret key
    remoteRef:
      key: carina-login-keytab
