apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: cephfs-static-pi
  namespace: slurm
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 498T
  volumeMode: Filesystem
  volumeName: cephfs-static-pi-slurm
