apiVersion: v1
data:
  docker-entrypoint.sh: "#!/bin/bash\nset -e\n\n#enable extrausers, just in case\n#sed
    -i '/^\\(passwd\\|group\\|shadow\\):/{ s/$/ extrausers/; }' /etc/nsswitch.conf\n\nif
    [ \"$1\" = \"munged\" ]\nthen\n    echo \"---> Starting the MUNGE Authentication
    service (munged) ...\"\n#    if [ ! -e /etc/munge/munge.key ]\n#    then\n#        /usr/sbin/create-munge-key\n#
    \   fi\n    #copy in munge key\n    #cp /local/munge-key/munge.key /etc/munge/munge.key\n
    \   #this should likely be removed, but had some issues with munge perms\n    #mkdir
    -p /var/run/munge\n    #chown -R munge:munge /etc/munge\n    #chmod 700 /etc/munge\n
    \   #chmod 400 /etc/munge/munge.key\n    #chown -R munge:munge /var/run/munge\n
    \   #chmod -R 755 /var/run/munge\n    exec /usr/sbin/munged -F\nfi\n\nif [ \"$1\"
    = \"slurmdbd\" ]\nthen\n    echo \"---> Starting the Slurm Database Daemon (slurmdbd)
    ...\"\n    exec gosu slurm /usr/sbin/slurmdbd -Dvvv\nfi\n\nif [ \"$1\" = \"slurmctld\"
    ]\nthen\n    echo \"---> Waiting for slurmdbd to become active before starting
    slurmctld ...\"\n\n#    until 2>/dev/null >/dev/tcp/slurmdbd/6819\n#    do\n#
    \       echo \"-- slurmdbd is not available.  Sleeping ...\"\n#        sleep 2\n#
    \   done\n#    echo \"-- slurmdbd is now active ...\"\n\n    #wait until munge
    socket is up\n    until [ -S /var/run/munge/munge.socket.2 ]\n    do\n      sleep
    2\n      echo \"waiting for munge to start\"\n    done\n\n    echo \"---> Starting
    the Slurm Controller Daemon (slurmctld) ...\"\n    exec gosu slurm /usr/sbin/slurmctld
    -iDvvv\nfi\n\nif [ \"$1\" = \"slurmd\" ]\nthen\n#add logic to check for /var/run/munge/munge.socket.2.lock
    and /var/run/slurmdbd/slurmdbd.pid \n#    echo \"---> Waiting for slurmctld to
    become active before starting slurmd...\"\n#    until 2>/dev/null >/dev/tcp/slurmctld/6817\n#
    \   do\n#        echo \"-- slurmctld is not available.  Sleeping ...\"\n#        sleep
    2\n#    done\n#    echo \"-- slurmctld is now active ...\"\n\n    echo \"--->
    Starting automount\"\n    cp /mnt/autofs/auto.* /etc\n    chmod 444 /etc/auto.*\n
    \   BROWSE_MODE=\"no\" /usr/sbin/automount -t 0 -f /etc/auto.master &\n\n    echo
    \"---> Starting the Slurm Node Daemon (slurmd) ...\"\n    #slurmd entry point
    for starting SLURM inside kubernetes\n    #note: /root/host-mappings should be
    somehow mounted into the container\n    #/etc/hostname on the host is mounted
    to /root/hostname\n    name=`cat /root/hostname`\n    slurmName=`grep $name /root/hosts/host-mappings
    | cut -f2 -d\" \"`\n    myip=$(awk '/32 host/ { print f } {f=$2}' <<< \"$(</proc/net/fib_trie)\"
    | sort | uniq  | grep -v 127.0.0.1)\n    #wait until munge socket is up\n    until
    [ -S /var/run/munge/munge.socket.2 ]\n    do\n      sleep 2\n      echo \"waiting
    for munge to start\"\n    done\n    echo \"DEBUG SCONTROL COMMAND: scontrol update
    nodename=$slurmName nodeaddr=$myip nodehostname=`hostname`\"\n    scontrol update
    nodename=$slurmName nodeaddr=$myip nodehostname=`hostname`\n    exec slurmd -D
    -N $slurmName\nfi\n\nif [ \"$1\" = \"slurmd-gke\" ]\nthen\n    echo \"---> Starting
    the Slurm Node Daemon (slurmd) ...\"\n    myip=$(awk '/32 host/ { print f } {f=$2}'
    <<< \"$(</proc/net/fib_trie)\" | sort | uniq  | grep -v 127.0.0.1)\n    #munge
    is starte in sibling container\n    #until [ -S /var/run/munge/munge.socket.2
    ]\n    #do\n    #  sleep 2\n    #  echo \"waiting for munge to start\"\n    #done\n
    \   echo \"DEBUG SCONTROL COMMAND: scontrol update nodename=$slurmName nodeaddr=$myip
    nodehostname=`hostname`\"\n    scontrol update nodename=\"nero-1\" nodeaddr=$myip
    nodehostname=`hostname`\n    scontrol update nodename=\"nero-1\" state=idle\n
    \   exec slurmd -D -N \"nero-1\"\nfi\n\n\nif [ \"$1\" = \"sshd\" ]\nthen\n#add
    logic to check for /var/run/munge/munge.socket.2.lock and /var/run/slurmdbd/slurmdbd.pid\n
    \   echo \"---> Starting automount\"\n    cp /mnt/autofs/auto.* /etc\n    chmod
    444 /etc/auto.*\n    BROWSE_MODE=\"no\" /usr/sbin/automount -t 0 -f /etc/auto.master
    &\n\n    #wait until munge socket is up\n    until [ -S /var/run/munge/munge.socket.2
    ]\n    do\n      sleep 2\n      echo \"waiting for munge to start\"\n    done\n
    \   #set fqdn to be stanford\n    hostname $HOSTNAME.stanford.edu\n    #need sshd
    directory in /run\n    mkdir  /run/sshd\n    echo \"---> Starting the OpenSSH
    Daemon (sshd) ...\"\n    exec  /usr/sbin/sshd -D -e\nfi\n\nexec \"$@\"\n"
kind: ConfigMap
metadata:
  annotations:
    configmanagement.gke.io/cluster-selector: slurm
  name: docker-entrypoint
  namespace: slurm
