apiVersion: v1
data:
  hosts: |
    # Kubernetes-managed hosts file.
    127.0.0.1	localhost
    ::1	localhost ip6-localhost ip6-loopback
    fe00::0	ip6-localnet
    fe00::0	ip6-mcastprefix
    fe00::1	ip6-allnodes
    fe00::2	ip6-allrouters
    10.4.9.8	carina

    10.112.1.142 secure-2
    10.112.1.143 secure-3
    10.112.1.152 secure-gpu-1
    10.112.1.153 secure-gpu-2
    # Entries added by HostAliases.
    127.0.0.1	test-rw.carina.stanford.edu
kind: ConfigMap
metadata:
  annotations:
    configmanagement.gke.io/cluster-selector: slurm
  name: etc-hosts
  namespace: slurm
