apiVersion: v1
data:
  host-mappings: |
    kn-b16-1-1 secure-1
    kn-b16-1-2 secure-2
    kn-b16-1-3 secure-3
    kn-b16-1-4 secure-4
    kn-b16-3-1 secure-5
    kn-b16-3-2 secure-6
    kn-b16-3-3 secure-7
    kn-b16-3-4 secure-8
    kn-b16-5-1 secure-9
    kn-b16-5-2 secure-10
    kn-b16-5-3 secure-11
    kn-b16-5-4 secure-12
    kn-b16-7-1 secure-13
    kn-b16-7-2 secure-14
    kn-b16-7-3 secure-15
    kn-b16-7-4 secure-16
    kn-b16-9-1 secure-gpu-1
    kn-b16-9-2 secure-gpu-2
    kn-b16-12 secure-gpu-3
    kn-b16-13 secure-gpu-4
    kn-b16-14 secure-gpu-5
    kn-b16-15 secure-gpu-6
    kn-b16-16 secure-gpu-7
    kn-b16-17 secure-gpu-8
    kn-b13-gpu-nigam secure-gpu-9
    kn-b13-gpu-boussard secure-gpu-10
    kn-b13-gpu-ogevaert secure-gpu-11
    kn-b14-gpu2-nigam secure-gpu-12
    kn-b14-gpu-mrivas secure-gpu-13
    kn-b13-studdert secure-17
    kn-b12-gpu3-nigam secure-gpu-14
    kn-b12-gpu-1 secure-gpu-15
    kn-b12-gpu-2 secure-gpu-16
    kn-b12-gpu-3 secure-gpu-17
    kn-b12-gpu-4 secure-gpu-18
    kn-b13-gpu-1 secure-gpu-19
    kn-b13-gpu-2 secure-gpu-20
kind: ConfigMap
metadata:
  annotations:
    configmanagement.gke.io/cluster-selector: slurm
  name: host-mappings
  namespace: slurm
