apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    configmanagement.gke.io/cluster-selector: slurm
  labels:
    networkaccess: none
  name: munged
  namespace: slurm
spec:
  selector:
    matchLabels:
      service: munged
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'runtime/default'            
      labels:
        service: munged
    spec:
      initContainers:
      - args:
        - /usr/local/bin/fix-munge.sh
        command:
        - /usr/bin/tini
        image: us-docker.pkg.dev/srcc-nero-prod/docker-repo/jupyter-20.04:production
        imagePullPolicy: Always
        name: munged-init
        securityContext:
          runAsGroup: 0
          runAsUser: 0
      # copy munge key and own it
      # give munge ownership of munge-key
        volumeMounts:
        - mountPath: /local/munge-key
          name: munge-key
        - mountPath: /etc/munge
          name: etc-munge
        - mountPath: /var/run/munge
          name: run-munge
        - mountPath: /run/munge
          name: run-munge
      containers:
      - args:
        - /usr/local/bin/docker-entrypoint.sh
        - munged
        command:
        - /usr/bin/tini
        image: us-docker.pkg.dev/srcc-nero-prod/docker-repo/jupyter-20.04:production
        imagePullPolicy: IfNotPresent
        name: munged
        securityContext:
          runAsGroup: 114
          runAsUser: 106
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 30m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        volumeMounts:
        - mountPath: /usr/local/bin/docker-entrypoint.sh
          name: docker-entrypoint
          subPath: docker-entrypoint.sh
        - mountPath: /etc/munge
          name: etc-munge
        - mountPath: /var/run/munge
          name: run-munge
        - mountPath: /run/munge
          name: run-munge
        - mountPath: /var/lib/extrausers
          name: extra-users
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: artifact-registry
      nodeSelector:
        srcc.stanford.edu/munged: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
#      securityContext:
#        privileged: false
#        runAsGroup: 106
#        runAsUser: 105
#        fsGroup: 109
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: nero.stanford.edu/login
        operator: Equal
        value: "true"
      - effect: NoSchedule
        key: carina.stanford.edu/login
        operator: Equal
        value: "true"
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: present
      volumes:
      - configMap:
          defaultMode: 365
          name: docker-entrypoint
        name: docker-entrypoint
      - emptyDir: {}
        name: temp
      - emptyDir: {}
        name: etc-munge
      - name: munge-key
        secret:
          defaultMode: 420
          secretName: munge-key
      - configMap:
          defaultMode: 365
          name: extrausers
        name: extra-users
      - hostPath:
          path: /mnt/srcc/munge
          type: Directory
        name: run-munge
