apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: mysql-root-password
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gsm-store              # name of the SecretStore (or kind specified)
  target:
    name: mysql-root-password  # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - key: mysql-root-password
