apiVersion: v1
data:
  nologin: |
    Carina On-Premise is currently under maintenance and will be back ASAP.
kind: ConfigMap
metadata:
  annotations:
    configmanagement.gke.io/cluster-selector: slurm
  name: nologin
  namespace: slurm
