---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-sw
  namespace: slurm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1024G
  volumeMode: Filesystem
  volumeName: slurm-share-sw
