---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: share-sw-nfs
  name: share-sw-nfs
  namespace: slurm
spec:
  replicas: 1
  selector:
    matchLabels:
      service: share-sw-nfs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: share-sw-nfs
    spec:
      containers:
      - image: us-docker.pkg.dev/srcc-nero-prod/docker-repo/docker-nfs-server:latest
        imagePullPolicy: Always
        name: nfs
        ports:
        - containerPort: 2049
          protocol: TCP
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /nfs
          name: share-sw
        - mountPath: /etc/exports
          name: exports
          subPath: exports
        - mountPath: /var/lib/extrausers
          name: extrausers
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: artifact-registry
      hostname: nfs
      nodeSelector:
        type: admin
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: share-sw
        persistentVolumeClaim:
          claimName: share-sw
      - name: extrausers
        configMap:
          name: extrausers
          defaultMode: 365
      - name: exports
        configMap:
          name: exports
          defaultMode: 365
