---
apiVersion: v1
kind: Service
metadata:
  labels:
    nfs: share-sw-nfs
  name: share-sw-nfs
  namespace: slurm
spec:
  type: ClusterIP
  clusterIP: 10.152.14.101
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
    targetPort: 2049
  selector:
    service: share-sw-nfs
  sessionAffinity: None
