apiVersion: v1
kind: Service
metadata:
  labels:
    service: slurmlogin-grusky-avp
  name: slurmlogin-grusky-avp
  namespace: slurm
  annotations:
    configmanagement.gke.io/cluster-selector: slurm
spec:
  clusterIP: 10.152.208.76
  clusterIPs:
  - 10.152.208.76
  loadBalancerIP: 10.112.1.229
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32563
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    networkservice: slurmlogin-grusky-avp
  sessionAffinity: None
  type: LoadBalancer
