apiVersion: v1
kind: Service
metadata:
  name: slurmcontroller
  namespace: slurm
spec:
  clusterIP: 10.152.183.156
  clusterIPs:
  - 10.152.183.156
  ports:
  - name: slurmctld
    port: 6817
    protocol: TCP
    targetPort: 6817
  - name: slurmctld-srun
    port: 60001
    protocol: TCP
    targetPort: 60001    
  - name: slurmdbd
    port: 6819
    protocol: TCP
    targetPort: 6819
  selector:
    service: slurmcontroller
  type: ClusterIP
