apiVersion: v1
data:
  docker.cnf: |
    [mysqld]
    skip-host-cache
    skip-name-resolve
  mysqld_safe_syslog.cnf: |
    [mysqld_safe]
    skip_log_error
    syslog
  timeouts.cnf: |
    [mysqld]
    #28800 = 8 hours
    #The number of seconds the server waits for activity on a connection before closing it
    wait_timeout=28800
    #The number of seconds the server waits for activity on an interactive connection before closing it.
    interactive_timeout=28800      
kind: ConfigMap
metadata:
  annotations:
    configmanagement.gke.io/cluster-selector: slurm
  name: slurm-mysql
  namespace: slurm
