apiVersion: v1
kind: Service
metadata:
  labels:
    service: slurmlogin
  name: slurmlogin
  namespace: slurm
  annotations:
    configmanagement.gke.io/cluster-selector: slurm
spec:
  clusterIP: 10.152.208.74
  clusterIPs:
  - 10.152.208.74
  loadBalancerIP: 10.112.1.228
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32561
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    networkservice: slurmlogin
  sessionAffinity: None
  type: LoadBalancer
