---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configmanagement.gke.io/cluster-selector: slurm
  labels:
    networkaccess: slurm
  name: slurmadmin
  namespace: slurm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      networkservice: slurmadmin
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'runtime/default'
      creationTimestamp: null
      labels:
        networkservice: slurmadmin
    spec:
      containers:
      - args:
        - /usr/local/bin/docker-entrypoint.sh
        - sshd
        command:
        - /usr/bin/tini
        image: us-docker.pkg.dev/srcc-nero-prod/docker-repo/jupyter-20.04:production
        imagePullPolicy: Always
        name: sshd
        ports:
        - containerPort: 22
          protocol: TCP
        resources:
          limits:
            cpu: "32"
            memory: 370000Mi
          requests:
            cpu: 4
            memory: 2048Mi
        securityContext:
          privileged: true #need to be true
          procMount: Default
          runAsGroup: 0
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/security/pam_duo.conf
          name: carina-login-duo
          readOnly: true
          subPath: pam_duo.conf
        - mountPath: /usr/share/lmod/lmod/modulefiles
          name: modulefiles
          readOnly: true
        - mountPath: /tmp
          name: temp
        - mountPath: /mnt/srcc
          name: srcc
        - mountPath: /etc/update-motd.d
          name: motd
        - mountPath: /home
          name: home
        - mountPath: /share/pi
          name: pi-share
          subPath: pi
        - mountPath: /share/data
          name: pi-share
          subPath: data
        - mountPath: /share/sw
          name: sw-share
          subPath: share/sw
          readOnly: false
        - mountPath: /etc/slurm-llnl
          name: etc-slurm
        - mountPath: /var/run/munge
          name: run-munge
        - mountPath: /var/lib/extrausers
          name: extra-users
          readOnly: true
        - mountPath: /etc/ssh
          name: sshd
        - mountPath: /var/log
          name: log
        - name: boto-cfg
          mountPath: /etc/gcloud/gsutil/boto.cfg
          subPath: boto.cfg
        - name: boto-sh
          mountPath: /etc/profile.d/boto.sh
          subPath: boto.sh
      tolerations:
      - effect: NoSchedule
        key: carina.stanford.edu/admin
        operator: Equal
        value: "true"
      hostAliases:
      - hostnames:
        - admin.carina.stanford.edu
        ip: 127.0.0.1
      hostname: carina
      nodeSelector:
        srcc.stanford.edu/munged: "true"
        type: admin
      imagePullSecrets:
      - name: artifact-registry
      volumes:
      - hostPath:
          path: /mnt/srcc/modulefiles
          type: Directory
        name: modulefiles
      - configMap:
          defaultMode: 365
          name: srcc.sh
        name: srcc
      - configMap:
          defaultMode: 365
          name: motd.d
        name: motd
      - emptyDir: {}
        name: temp
      - name: home
        persistentVolumeClaim:
          claimName: cephfs-static-home
      - name: pi-share
        persistentVolumeClaim:
          claimName: cephfs-static-pi
      - name: sw-share
        nfs:
          server: 10.152.14.101
          path: /
      - name: carina-login-duo
        secret:
          defaultMode: 384
          secretName: carina-login-duo
      - name: munge-key
        secret:
          defaultMode: 420
          secretName: munge-key
      - configMap:
          defaultMode: 365
          name: extrausers
        name: extra-users
      - configMap:
          defaultMode: 365
          name: slurm-node-conf
        name: etc-slurm
      - configMap:
          defaultMode: 384
          name: sshd-admin
        name: sshd
      - hostPath:
          path: /mnt/srcc/munge
          type: Directory
        name: run-munge
      - emptyDir: {}
        name: log
      - configMap:
          defaultMode: 365
          name: rsyslog
        name: rsyslog
      - configMap:
          defaultMode: 365
          name: logrotate
        name: logrotate
      - name: boto-cfg
        configMap:
          name: boto-cfg
          defaultMode: 420
          items:
          - key: boto.cfg
            path: boto.cfg
      - name: boto-sh
        configMap:
          name: boto-cfg
          defaultMode: 420
          items:
          - key: boto.sh
            path: boto.sh
